export const ENROLLMENT_STATUSES = Object.freeze({
  PENDING: "pending",
  ACTIVE: "active",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
});

export const ENROLLMENT_STATUS_TRANSITIONS = Object.freeze({
  [ENROLLMENT_STATUSES.PENDING]: Object.freeze([
    ENROLLMENT_STATUSES.ACTIVE,
    ENROLLMENT_STATUSES.CANCELLED,
  ]),
  [ENROLLMENT_STATUSES.ACTIVE]: Object.freeze([
    ENROLLMENT_STATUSES.COMPLETED,
    ENROLLMENT_STATUSES.CANCELLED,
  ]),
  [ENROLLMENT_STATUSES.COMPLETED]: Object.freeze([]),
  [ENROLLMENT_STATUSES.CANCELLED]: Object.freeze([]),
});
