import { MEMBERSHIP_ROLES } from "./membership.js";
import { CAPABILITY_IDS } from "./capabilities.js";
import { PLATFORM_ROLES } from "./authorization.js";

const freezeCapabilities = (capabilities) => Object.freeze(capabilities);

export const ROLE_CAPABILITY_MATRIX = Object.freeze({
  membershipRoles: Object.freeze({
    [MEMBERSHIP_ROLES.STUDENT]: freezeCapabilities([
      CAPABILITY_IDS.MEMBERSHIP_READ_SELF,
      CAPABILITY_IDS.COURSE_LIST,
      CAPABILITY_IDS.COURSE_READ,
      CAPABILITY_IDS.ENROLLMENT_READ_SELF,
      CAPABILITY_IDS.ENROLLMENT_CANCEL_SELF,
    ]),
    [MEMBERSHIP_ROLES.TEACHER]: freezeCapabilities([
      CAPABILITY_IDS.MEMBERSHIP_READ_SELF,
      CAPABILITY_IDS.COURSE_LIST,
      CAPABILITY_IDS.COURSE_READ,
      CAPABILITY_IDS.COURSE_CREATE,
      CAPABILITY_IDS.COURSE_UPDATE,
      CAPABILITY_IDS.ENROLLMENT_READ_SELF,
      CAPABILITY_IDS.ENROLLMENT_LIST,
      CAPABILITY_IDS.ENROLLMENT_CANCEL_SELF,
    ]),
    [MEMBERSHIP_ROLES.TENANT_ADMIN]: freezeCapabilities([
      CAPABILITY_IDS.TENANT_READ,
      CAPABILITY_IDS.TENANT_UPDATE,
      CAPABILITY_IDS.TENANT_MANAGE_SETTINGS,
      CAPABILITY_IDS.TENANT_MANAGE_BRANDING,
      CAPABILITY_IDS.MEMBERSHIP_READ_SELF,
      CAPABILITY_IDS.MEMBERSHIP_LIST,
      CAPABILITY_IDS.MEMBERSHIP_SUSPEND,
      CAPABILITY_IDS.MEMBERSHIP_RESTORE,
      CAPABILITY_IDS.MEMBERSHIP_REMOVE,
      CAPABILITY_IDS.MEMBERSHIP_CHANGE_ROLE,
      CAPABILITY_IDS.REGISTRATION_REQUEST_LIST,
      CAPABILITY_IDS.REGISTRATION_REQUEST_REVIEW,
      CAPABILITY_IDS.COURSE_LIST,
      CAPABILITY_IDS.COURSE_READ,
      CAPABILITY_IDS.COURSE_CREATE,
      CAPABILITY_IDS.COURSE_UPDATE,
      CAPABILITY_IDS.COURSE_ACTIVATE,
      CAPABILITY_IDS.COURSE_ARCHIVE,
      CAPABILITY_IDS.ENROLLMENT_READ_SELF,
      CAPABILITY_IDS.ENROLLMENT_LIST,
      CAPABILITY_IDS.ENROLLMENT_CREATE,
      CAPABILITY_IDS.ENROLLMENT_UPDATE_STATUS,
      CAPABILITY_IDS.ENROLLMENT_CANCEL_SELF,
    ]),
  }),
  platformRoles: Object.freeze({
    [PLATFORM_ROLES.PLATFORM_ADMIN]: freezeCapabilities([
      CAPABILITY_IDS.PLATFORM_TENANT_LIST,
      CAPABILITY_IDS.PLATFORM_TENANT_READ,
      CAPABILITY_IDS.PLATFORM_TENANT_CREATE,
      CAPABILITY_IDS.PLATFORM_TENANT_UPDATE,
      CAPABILITY_IDS.PLATFORM_TENANT_SUSPEND,
      CAPABILITY_IDS.PLATFORM_TENANT_RESTORE,
      CAPABILITY_IDS.PLATFORM_TENANT_ARCHIVE,
      CAPABILITY_IDS.PLATFORM_IDENTITY_READ,
    ]),
  }),
});
