import assert from "node:assert/strict";import test from "node:test";
import { PLATFORM_AUTHORITY_REGISTRY_SCHEMA_VERSION, PLATFORM_AUTHORITY_REGISTRY_STATES, PLATFORM_AUTHORITY_SCHEMA_VERSION } from "@mipymetic/saas-contracts/authority";
import { CAPABILITY_IDS } from "@mipymetic/saas-contracts/domain";
import { identityDocumentPath, membershipKeyDocumentPath, platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath, tenantAdminAuthorityStateDocumentPath, tenantAuditEventDocumentPath, tenantBrandingDocumentPath, tenantDocumentPath, tenantSettingsDocumentPath } from "@mipymetic/saas-contracts/persistence";
import { executeBootstrapTenant, parseBootstrapTenantInput, type BootstrapTenantDependencies } from "../commands/bootstrapTenant.js";
import { createFirestoreBootstrapIdentityPort, type BootstrapAuthUser } from "../commands/bootstrapPlatformAdmins.js";
import { createTenantBootstrapTransactionStore } from "../persistence/tenantBootstrapTransactionStore.js";
import type { AuthoritativeReaderPort, DocumentSnapshotPort, TransactionPort, TransactionRunnerPort } from "../persistence/ports.js";
import type { JsonValue } from "../contracts/types.js";import { BackendError } from "../errors/backendError.js";
import { BACKEND_ERROR_CODES } from "@mipymetic/saas-contracts/errors";
const now="2026-08-13T12:00:00.000Z";
class Memory implements TransactionRunnerPort,AuthoritativeReaderPort,TransactionPort{readonly docs=new Map<string,Readonly<Record<string,unknown>>>();readonly creates:string[]=[];async run<T>(fn:(t:TransactionPort)=>Promise<T>){return fn(this)}async read(path:string){return this.snap(path)}async get(path:string){return this.snap(path)}private snap(path:string):DocumentSnapshotPort{const data=this.docs.get(path);return Object.freeze({exists:data!==undefined,data:(data??null) as Readonly<Record<string,JsonValue>>|null})}create(path:string,data:Readonly<Record<string,unknown>>){if(this.docs.has(path))throw new Error("exists");this.creates.push(path);this.docs.set(path,data)}set(path:string,data:Readonly<Record<string,unknown>>){this.docs.set(path,data)}update(path:string,data:Readonly<Record<string,unknown>>){this.docs.set(path,{...this.docs.get(path),...data})}}
const identity=(uid:string,email:string)=>({uid,email,displayName:uid,photoURL:null,emailVerified:true,interfaceLocale:"en",createdAt:now,updatedAt:now});
const authority=(uid:string)=>({schemaVersion:PLATFORM_AUTHORITY_SCHEMA_VERSION,transitionCommandId:null,uid,authority:"platform_admin",status:"active",createdAt:now,createdBy:"seed",updatedAt:now,updatedBy:"seed",activatedAt:now,revokedAt:null,revokedBy:null,bootstrapCommandId:"bootstrap",lastClaimSyncAt:now});
const registry=()=>({schemaVersion:PLATFORM_AUTHORITY_REGISTRY_SCHEMA_VERSION,bootstrapState:PLATFORM_AUTHORITY_REGISTRY_STATES.COMPLETED,activeCount:2,revision:1,lastCommandId:"bootstrap",updatedAt:now});
const input=()=>({commandId:"tenant-bootstrap-1",correlationId:"correlation-1",tenantId:"tenant-1",tenant:{tenantType:"university",displayName:"Tenant",shortName:"T",country:"PL",locale:"pl-PL",timezone:"Europe/Warsaw"},settings:{defaultLocale:"pl-PL",registrationPolicy:{openRegistration:false,invitationOnly:false,institutionalEmailOnly:false,manualApprovalRequired:true},featureFlags:{beta:false},supportEmail:null,supportUrl:null},branding:{displayName:null,logoUrl:null,faviconUrl:null,colors:{primary:"#000",secondary:"#fff",accent:"#f00"}},firstAdminUid:"admin-b",expectedAdminEmail:"admin-b@example.com",initialStatus:"active"});
const setup=()=>{const memory=new Memory();memory.docs.set(identityDocumentPath("admin-a"),identity("admin-a","admin-a@example.com"));memory.docs.set(identityDocumentPath("admin-b"),identity("admin-b","admin-b@example.com"));memory.docs.set(platformAuthorityDocumentPath("admin-a"),authority("admin-a"));memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const users=new Map<string,BootstrapAuthUser>([["admin-a",{uid:"admin-a",email:"admin-a@example.com",emailVerified:true,disabled:false,customClaims:{}}],["admin-b",{uid:"admin-b",email:"admin-b@example.com",emailVerified:true,disabled:false,customClaims:{}}]]);const deps:BootstrapTenantDependencies={authContext:{uid:"admin-a",token:{email_verified:true}},reader:memory,auth:{getUser:async(uid)=>users.get(uid)!},identity:createFirestoreBootstrapIdentityPort(memory),store:createTenantBootstrapTransactionStore(memory),generateMembershipId:()=>"membership-1"};return{memory,deps}};
test("BootstrapTenant package input rejects unknown and malformed identifiers",()=>{assert.throws(()=>parseBootstrapTenantInput({...input(),actor:"spoof"}),BackendError);for(const bad of [""," ",".","..","a/b"])assert.throws(()=>parseBootstrapTenantInput({...input(),tenantId:bad}),BackendError)});
test("BootstrapTenant creates one complete aggregate and two sanitized audits",async()=>{const{memory,deps}=setup();const value=await executeBootstrapTenant(input(),deps);assert.deepEqual(value,{commandId:"tenant-bootstrap-1",correlationId:"correlation-1",operation:"BootstrapTenant",resourceType:"tenant",resourceId:"tenant-1",status:"succeeded",replayed:false});for(const path of [tenantDocumentPath("tenant-1"),tenantSettingsDocumentPath("tenant-1"),tenantBrandingDocumentPath("tenant-1"),membershipKeyDocumentPath("tenant-1","u1_YWRtaW4tYg"),tenantAdminAuthorityStateDocumentPath("tenant-1"),privilegedCommandDocumentPath("tenant-bootstrap-1"),tenantAuditEventDocumentPath("tenant-1","tenant-bootstrap-1-tenant-create")])assert.equal(memory.docs.has(path),true);assert.equal(memory.docs.get(tenantAdminAuthorityStateDocumentPath("tenant-1"))?.activeCount,1);assert.equal(memory.docs.get(privilegedCommandDocumentPath("tenant-bootstrap-1"))?.status,"succeeded");assert.equal(memory.creates.length,9);assert.equal(JSON.stringify([...memory.docs.values()]).includes("admin-b@example.com"),true);const audits=[...memory.docs.entries()].filter(([path])=>path.includes("AuditEvent")||path.includes("auditEvents"));assert.equal(audits.length,2);assert.equal(JSON.stringify(audits).includes("@"),false)});
test("invalid evidence and aggregate collisions write nothing",async()=>{for(const mutate of [(m:Memory)=>m.docs.delete(identityDocumentPath("admin-b")),(m:Memory)=>m.docs.set(tenantDocumentPath("tenant-1"),{bad:true})]){const{memory,deps}=setup();mutate(memory);const before=memory.docs.size;await assert.rejects(executeBootstrapTenant(input(),deps),BackendError);assert.equal(memory.docs.size,before);assert.equal(memory.docs.has(privilegedCommandDocumentPath("tenant-bootstrap-1")),false)}});
test("capability absence fails before transaction writes",async()=>{const{memory,deps}=setup();memory.docs.set(platformAuthorityDocumentPath("admin-a"),{...authority("admin-a"),authority:"platform_system"});await assert.rejects(executeBootstrapTenant(input(),deps),BackendError);assert.equal(memory.creates.length,0);assert.equal(CAPABILITY_IDS.PLATFORM_TENANT_CREATE,"platform.tenant_create")});
test("BootstrapTenant rejects every incoherent persisted replay result without writes",async()=>{const variants=[
  (r:Readonly<Record<string,unknown>>)=>({...r,commandId:"foreign-command"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,correlationId:"foreign-correlation"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,operation:"RecoverPlatformAdmin"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,resourceType:"platform_authority"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,resourceId:"foreign-tenant"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,status:"failed"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,replayed:true}),
  (r:Readonly<Record<string,unknown>>)=>Object.fromEntries(Object.entries(r).filter(([field])=>field!=="resourceId")),
  (r:Readonly<Record<string,unknown>>)=>({...r,extra:true}),
  (r:Readonly<Record<string,unknown>>)=>({...r,commandId:"a/b"}),
];for(const mutate of variants){const{memory,deps}=setup();await executeBootstrapTenant(input(),deps);const path=privilegedCommandDocumentPath("tenant-bootstrap-1"),command=memory.docs.get(path)!;memory.docs.set(path,{...command,startedAt:now,completedAt:now,result:mutate(command.result as Readonly<Record<string,unknown>>)});const before=JSON.stringify([...memory.docs]);memory.creates.length=0;await assert.rejects(executeBootstrapTenant(input(),deps),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(JSON.stringify([...memory.docs]),before);assert.equal(memory.creates.length,0)}});
test("valid BootstrapTenant replay is read-only and preserves canonical persisted result",async()=>{const{memory,deps}=setup();await executeBootstrapTenant(input(),deps);const path=privilegedCommandDocumentPath("tenant-bootstrap-1"),command=memory.docs.get(path)!;memory.docs.set(path,{...command,startedAt:now,completedAt:now});const before=structuredClone(memory.docs.get(path));memory.creates.length=0;const replay=await executeBootstrapTenant(input(),deps);assert.deepEqual(replay,{commandId:"tenant-bootstrap-1",correlationId:"correlation-1",operation:"BootstrapTenant",resourceType:"tenant",resourceId:"tenant-1",status:"succeeded",replayed:true});assert.deepEqual(memory.docs.get(path),before);assert.equal((memory.docs.get(path)?.result as Readonly<Record<string,unknown>>).replayed,false);assert.equal(memory.creates.length,0)});
