import assert from "node:assert/strict";import test from "node:test";
import { PLATFORM_AUTHORITY_REGISTRY_SCHEMA_VERSION, PLATFORM_AUTHORITY_REGISTRY_STATES, PLATFORM_AUTHORITY_SCHEMA_VERSION } from "@mipymetic/saas-contracts/authority";
import { CAPABILITY_IDS, ROLE_CAPABILITY_MATRIX } from "@mipymetic/saas-contracts/domain";
import { identityDocumentPath, membershipKeyDocumentPath, platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath, tenantAdminAuthorityStateDocumentPath, tenantAuditEventDocumentPath, tenantBrandingDocumentPath, tenantDocumentPath, tenantSettingsDocumentPath } from "@mipymetic/saas-contracts/persistence";
import { executeBootstrapTenant, parseBootstrapTenantInput, type BootstrapTenantDependencies } from "../commands/bootstrapTenant.js";
import { createFirestoreBootstrapIdentityPort, type BootstrapAuthUser } from "../commands/bootstrapPlatformAdmins.js";
import { createTenantBootstrapTransactionStore, type BootstrapTenantAggregate } from "../persistence/tenantBootstrapTransactionStore.js";
import { serverOwnedTimestamp, type AuthoritativeReaderPort, type DocumentSnapshotPort, type TransactionPort, type TransactionRunnerPort } from "../persistence/ports.js";
import type { JsonValue } from "../contracts/types.js";import { BackendError } from "../errors/backendError.js";
import { BACKEND_ERROR_CODES } from "@mipymetic/saas-contracts/errors";
import { BOOTSTRAP_TENANT_AUDIT_AFTER_FIELDS, BOOTSTRAP_TENANT_AUDIT_BEFORE_FIELDS, BOOTSTRAP_TENANT_AUDIT_LEVEL, BOOTSTRAP_TENANT_AUDIT_METADATA_FIELDS, BOOTSTRAP_TENANT_AUDIT_OPERATION, BOOTSTRAP_TENANT_AUDIT_RESULT, BOOTSTRAP_TENANT_RESOURCE_TYPE } from "@mipymetic/saas-contracts/commands";
const now="2026-08-13T12:00:00.000Z";
class Memory implements TransactionRunnerPort,AuthoritativeReaderPort,TransactionPort{readonly docs=new Map<string,Readonly<Record<string,unknown>>>();readonly creates:string[]=[];async run<T>(fn:(t:TransactionPort)=>Promise<T>){return fn(this)}async read(path:string){return this.snap(path)}async get(path:string){return this.snap(path)}private snap(path:string):DocumentSnapshotPort{const data=this.docs.get(path);return Object.freeze({exists:data!==undefined,data:(data??null) as Readonly<Record<string,JsonValue>>|null})}create(path:string,data:Readonly<Record<string,unknown>>){if(this.docs.has(path))throw new Error("exists");this.creates.push(path);this.docs.set(path,data)}set(path:string,data:Readonly<Record<string,unknown>>){this.docs.set(path,data)}update(path:string,data:Readonly<Record<string,unknown>>){this.docs.set(path,{...this.docs.get(path),...data})}}
const identity=(uid:string,email:string)=>({uid,email,displayName:uid,photoURL:null,emailVerified:true,interfaceLocale:"en",createdAt:now,updatedAt:now});
const authority=(uid:string)=>({schemaVersion:PLATFORM_AUTHORITY_SCHEMA_VERSION,transitionCommandId:null,uid,authority:"platform_admin",status:"active",createdAt:now,createdBy:"seed",updatedAt:now,updatedBy:"seed",activatedAt:now,revokedAt:null,revokedBy:null,bootstrapCommandId:"bootstrap",lastClaimSyncAt:now});
const registry=()=>({schemaVersion:PLATFORM_AUTHORITY_REGISTRY_SCHEMA_VERSION,bootstrapState:PLATFORM_AUTHORITY_REGISTRY_STATES.COMPLETED,activeCount:2,revision:1,lastCommandId:"bootstrap",updatedAt:now});
const input=()=>({commandId:"tenant-bootstrap-1",correlationId:"correlation-1",tenantId:"tenant-1",tenant:{tenantType:"university",displayName:"Tenant",shortName:"T",country:"PL",locale:"pl-PL",timezone:"Europe/Warsaw"},settings:{defaultLocale:"pl-PL",registrationPolicy:{openRegistration:false,invitationOnly:false,institutionalEmailOnly:false,manualApprovalRequired:true},featureFlags:{beta:false},supportEmail:null,supportUrl:null},branding:{displayName:null,logoUrl:null,faviconUrl:null,colors:{primary:"#000",secondary:"#fff",accent:"#f00"}},firstAdminUid:"admin-b",expectedAdminEmail:"admin-b@example.com",initialStatus:"active"});
const setup=()=>{const memory=new Memory();memory.docs.set(identityDocumentPath("admin-a"),identity("admin-a","admin-a@example.com"));memory.docs.set(identityDocumentPath("admin-b"),identity("admin-b","admin-b@example.com"));memory.docs.set(platformAuthorityDocumentPath("admin-a"),authority("admin-a"));memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const users=new Map<string,BootstrapAuthUser>([["admin-a",{uid:"admin-a",email:"admin-a@example.com",emailVerified:true,disabled:false,customClaims:{}}],["admin-b",{uid:"admin-b",email:"admin-b@example.com",emailVerified:true,disabled:false,customClaims:{}}]]);const deps:BootstrapTenantDependencies={authContext:{uid:"admin-a",token:{email_verified:true}},reader:memory,auth:{getUser:async(uid)=>users.get(uid)!},identity:createFirestoreBootstrapIdentityPort(memory),store:createTenantBootstrapTransactionStore(memory),generateMembershipId:()=>"membership-1"};return{memory,deps}};
const canonicalPlatformActor=()=>Object.freeze({actorUid:"admin-a",actorType:"platform_admin" as const,authority:"platform_admin",tenantId:null,roles:Object.freeze(["platform_admin"]),capabilities:ROLE_CAPABILITY_MATRIX.platformRoles.platform_admin});
const aggregate=():BootstrapTenantAggregate=>{const timestamp=serverOwnedTimestamp();return{commandId:"tenant-bootstrap-1",correlationId:"correlation-1",payloadHash:"a".repeat(64),tenantId:"tenant-1",membershipId:"membership-1",uidKey:"u1_YWRtaW4tYg",actor:canonicalPlatformActor(),tenant:{tenantId:"tenant-1",tenantType:"university",displayName:"Tenant",shortName:"T",country:"PL",locale:"pl-PL",timezone:"Europe/Warsaw",status:"active",createdAt:timestamp,updatedAt:timestamp,suspendedAt:null,archivedAt:null},settings:{tenantId:"tenant-1",defaultLocale:"pl-PL",registrationPolicy:{openRegistration:false,invitationOnly:false,institutionalEmailOnly:false,manualApprovalRequired:true},featureFlags:{beta:false},supportEmail:null,supportUrl:null,updatedAt:timestamp},branding:{tenantId:"tenant-1",displayName:null,logoUrl:null,faviconUrl:null,colors:{primary:"#000",secondary:"#fff",accent:"#f00"},updatedAt:timestamp},membership:{membershipId:"membership-1",tenantId:"tenant-1",uid:"admin-b",role:"tenant_admin",status:"approved",originRequestId:null,createdAt:timestamp,approvedAt:timestamp,approvedBy:"admin-a",updatedAt:timestamp,suspendedAt:null,removedAt:null},membershipKey:{tenantId:"tenant-1",uid:"admin-b",membershipId:"membership-1",status:"approved",originRequestId:null,updatedAt:timestamp},authorityState:{tenantId:"tenant-1",activeCount:1,revision:1,lastCommandId:"tenant-bootstrap-1",updatedAt:timestamp},result:{commandId:"tenant-bootstrap-1",correlationId:"correlation-1",operation:"BootstrapTenant",resourceType:"tenant",resourceId:"tenant-1",status:"succeeded",replayed:false}}};
test("BootstrapTenant package input rejects unknown and malformed identifiers",()=>{assert.throws(()=>parseBootstrapTenantInput({...input(),actor:"spoof"}),BackendError);for(const bad of [""," ",".","..","a/b"])assert.throws(()=>parseBootstrapTenantInput({...input(),tenantId:bad}),BackendError)});
test("BootstrapTenant creates one complete aggregate and two package-authoritative sanitized audits",async()=>{const{memory,deps}=setup();const value=await executeBootstrapTenant(input(),deps);assert.deepEqual(value,{commandId:"tenant-bootstrap-1",correlationId:"correlation-1",operation:"BootstrapTenant",resourceType:"tenant",resourceId:"tenant-1",status:"succeeded",replayed:false});for(const path of [tenantDocumentPath("tenant-1"),tenantSettingsDocumentPath("tenant-1"),tenantBrandingDocumentPath("tenant-1"),membershipKeyDocumentPath("tenant-1","u1_YWRtaW4tYg"),tenantAdminAuthorityStateDocumentPath("tenant-1"),privilegedCommandDocumentPath("tenant-bootstrap-1"),tenantAuditEventDocumentPath("tenant-1","tenant-bootstrap-1-tenant-create")])assert.equal(memory.docs.has(path),true);assert.equal(memory.docs.get(tenantAdminAuthorityStateDocumentPath("tenant-1"))?.activeCount,1);const command=memory.docs.get(privilegedCommandDocumentPath("tenant-bootstrap-1"))!;assert.equal(command.status,"succeeded");assert.deepEqual([command.actorUid,command.actorType,command.authority],["admin-a","platform_admin","platform_admin"]);assert.equal(memory.creates.length,9);assert.equal(JSON.stringify([...memory.docs.values()]).includes("admin-b@example.com"),true);const audits=[...memory.docs.entries()].filter(([path])=>path.includes("AuditEvent")||path.includes("auditEvents"));assert.equal(audits.length,2);for(const[,audit]of audits){assert.deepEqual([audit.actorUid,audit.actorType,audit.authority],["admin-a","platform_admin","platform_admin"]);assert.equal(audit.level,BOOTSTRAP_TENANT_AUDIT_LEVEL);assert.equal(audit.operation,BOOTSTRAP_TENANT_AUDIT_OPERATION);assert.equal(audit.result,BOOTSTRAP_TENANT_AUDIT_RESULT);assert.equal(audit.resourceType,BOOTSTRAP_TENANT_RESOURCE_TYPE);assert.deepEqual(Object.keys(audit.beforeSummary as object),[...BOOTSTRAP_TENANT_AUDIT_BEFORE_FIELDS]);assert.deepEqual(Object.keys(audit.afterSummary as object),[...BOOTSTRAP_TENANT_AUDIT_AFTER_FIELDS]);assert.deepEqual(Object.keys(audit.metadata as object),[...BOOTSTRAP_TENANT_AUDIT_METADATA_FIELDS])}assert.equal(JSON.stringify(audits).includes("@"),false)});
test("invalid evidence and aggregate collisions write nothing",async()=>{for(const mutate of [(m:Memory)=>m.docs.delete(identityDocumentPath("admin-b")),(m:Memory)=>m.docs.set(tenantDocumentPath("tenant-1"),{bad:true})]){const{memory,deps}=setup();mutate(memory);const before=memory.docs.size;await assert.rejects(executeBootstrapTenant(input(),deps),BackendError);assert.equal(memory.docs.size,before);assert.equal(memory.docs.has(privilegedCommandDocumentPath("tenant-bootstrap-1")),false)}});
test("capability absence fails before transaction writes",async()=>{const{memory,deps}=setup();memory.docs.set(platformAuthorityDocumentPath("admin-a"),{...authority("admin-a"),authority:"platform_system"});await assert.rejects(executeBootstrapTenant(input(),deps),BackendError);assert.equal(memory.creates.length,0);assert.equal(CAPABILITY_IDS.PLATFORM_TENANT_CREATE,"platform.tenant_create")});
test("BootstrapTenant rejects every incoherent persisted replay result without writes",async()=>{const variants=[
  (r:Readonly<Record<string,unknown>>)=>({...r,commandId:"foreign-command"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,correlationId:"foreign-correlation"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,operation:"RecoverPlatformAdmin"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,resourceType:"platform_authority"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,resourceId:"foreign-tenant"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,status:"failed"}),
  (r:Readonly<Record<string,unknown>>)=>({...r,replayed:true}),
  (r:Readonly<Record<string,unknown>>)=>Object.fromEntries(Object.entries(r).filter(([field])=>field!=="resourceId")),
  (r:Readonly<Record<string,unknown>>)=>({...r,extra:true}),
  (r:Readonly<Record<string,unknown>>)=>({...r,commandId:"a/b"}),
];for(const mutate of variants){const{memory,deps}=setup();await executeBootstrapTenant(input(),deps);const path=privilegedCommandDocumentPath("tenant-bootstrap-1"),command=memory.docs.get(path)!;memory.docs.set(path,{...command,startedAt:now,completedAt:now,result:mutate(command.result as Readonly<Record<string,unknown>>)});const before=JSON.stringify([...memory.docs]);memory.creates.length=0;await assert.rejects(executeBootstrapTenant(input(),deps),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(JSON.stringify([...memory.docs]),before);assert.equal(memory.creates.length,0)}});
test("valid BootstrapTenant replay is read-only and preserves canonical persisted result",async()=>{const{memory,deps}=setup();await executeBootstrapTenant(input(),deps);const path=privilegedCommandDocumentPath("tenant-bootstrap-1"),command=memory.docs.get(path)!;memory.docs.set(path,{...command,startedAt:now,completedAt:now});const before=structuredClone(memory.docs.get(path));memory.creates.length=0;const replay=await executeBootstrapTenant(input(),deps);assert.deepEqual(replay,{commandId:"tenant-bootstrap-1",correlationId:"correlation-1",operation:"BootstrapTenant",resourceType:"tenant",resourceId:"tenant-1",status:"succeeded",replayed:true});assert.deepEqual(memory.docs.get(path),before);assert.equal((memory.docs.get(path)?.result as Readonly<Record<string,unknown>>).replayed,false);assert.equal(memory.creates.length,0)});
test("Tenant Store rejects every malformed NEW aggregate before its first write",async()=>{const mutations:Array<(value:BootstrapTenantAggregate)=>BootstrapTenantAggregate>=[
  value=>({...value,tenant:{...value.tenant,status:"archived"}}),value=>({...value,settings:{}}),value=>({...value,branding:{...value.branding,extra:true}}),
  value=>({...value,membership:{...value.membership,role:"owner"}}),value=>({...value,membership:{...value.membership,status:"suspended"}}),value=>({...value,membership:{...value.membership,uid:"foreign"}}),value=>({...value,membership:{...value.membership,originRequestId:"request-1"}}),
  value=>({...value,membershipKey:{...value.membershipKey,membershipId:"foreign"}}),value=>({...value,uidKey:"admin-b"}),value=>({...value,membershipKey:{...value.membershipKey,uid:"foreign"}}),
  value=>({...value,authorityState:{...value.authorityState,activeCount:2}}),value=>({...value,authorityState:{...value.authorityState,revision:0}}),value=>({...value,authorityState:{...value.authorityState,lastCommandId:"foreign"}}),
  value=>({...value,settings:{...value.settings,tenantId:"foreign"}}),value=>({...value,branding:{...value.branding,tenantId:"foreign"}}),value=>({...value,membership:{...value.membership,tenantId:"foreign"}}),
  value=>({...value,tenant:{...value.tenant,createdAt:{}}}),value=>({...value,tenant:Object.fromEntries(Object.entries(value.tenant).filter(([field])=>field!=="updatedAt"))}),value=>({...value,tenant:{...value.tenant,displayName:serverOwnedTimestamp()}}),
];for(const mutate of mutations){const memory=new Memory();memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const before=structuredClone([...memory.docs]);await assert.rejects(createTenantBootstrapTransactionStore(memory).execute(mutate(aggregate())),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.deepEqual([...memory.docs],before);assert.equal(memory.creates.length,0)}});
test("Tenant Store validates the complete NEW aggregate then writes exactly nine documents",async()=>{const memory=new Memory();memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const outcome=await createTenantBootstrapTransactionStore(memory).execute(aggregate());assert.equal(outcome.replayed,false);assert.equal(memory.creates.length,9);assert.equal(memory.docs.get(tenantAdminAuthorityStateDocumentPath("tenant-1"))?.activeCount,1)});
test("Tenant Store rejects forged BootstrapTenant authority before every write",async()=>{const memory=new Memory();memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const value=aggregate(),forged={...value,actor:{...value.actor,authority:"forged_authority",roles:[],capabilities:[]},membership:{...value.membership,approvedBy:"admin-a"}} as BootstrapTenantAggregate;await assert.rejects(createTenantBootstrapTransactionStore(memory).execute(forged),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(memory.creates.length,0);assert.equal(memory.docs.size,1)});
test("Tenant Store rejects the complete invalid actor matrix with zero writes",async()=>{const canonical=canonicalPlatformActor(),caps=[...canonical.capabilities],without=(field:string)=>Object.fromEntries(Object.entries(canonical).filter(([key])=>key!==field));const invalid:readonly unknown[]=[
  {...canonical,actorType:"identity"},{...canonical,tenantId:"tenant-1"},
  {actorUid:"admin-a",actorType:"identity",authority:"tenant_admin",tenantId:"tenant-1",roles:["tenant_admin"],capabilities:ROLE_CAPABILITY_MATRIX.membershipRoles.tenant_admin},
  {actorUid:"admin-a",actorType:"identity",authority:"teacher",tenantId:"tenant-1",roles:["teacher"],capabilities:ROLE_CAPABILITY_MATRIX.membershipRoles.teacher},
  {actorUid:"admin-a",actorType:"identity",authority:"student",tenantId:"tenant-1",roles:["student"],capabilities:ROLE_CAPABILITY_MATRIX.membershipRoles.student},
  {actorUid:"operator",actorType:"system",authority:"platform_system",tenantId:null,roles:[],capabilities:[]},
  {actorUid:"operator",actorType:"system",authority:"platform_recovery",tenantId:null,roles:[],capabilities:[]},
  {...canonical,roles:[]},{...canonical,roles:["platform_admin","platform_admin"]},
  {...canonical,capabilities:caps.filter(value=>value!==CAPABILITY_IDS.PLATFORM_TENANT_CREATE)},
  {...canonical,capabilities:[...caps,"tenant.update"]},{...canonical,capabilities:[...caps].reverse()},
  {...canonical,capabilities:[...caps,caps[0]]},{...canonical,actorUid:"a/b"},
  {...canonical,extra:true},without("authority"),{...canonical,roles:"platform_admin"},
];for(const actor of invalid){const memory=new Memory();memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const value={...aggregate(),actor} as BootstrapTenantAggregate;await assert.rejects(createTenantBootstrapTransactionStore(memory).execute(value),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(memory.creates.length,0);assert.deepEqual([...memory.docs.keys()],[platformAuthorityRegistryDocumentPath()])}});
test("Tenant Store binds Membership approval and replay Command actor before writes",async()=>{const memory=new Memory();memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const mismatched={...aggregate(),membership:{...aggregate().membership,approvedBy:"other"}};await assert.rejects(createTenantBootstrapTransactionStore(memory).execute(mismatched),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(memory.creates.length,0);await createTenantBootstrapTransactionStore(memory).execute(aggregate());const path=privilegedCommandDocumentPath("tenant-bootstrap-1"),command=memory.docs.get(path)!;memory.docs.set(path,{...command,actorUid:"other",startedAt:now,completedAt:now});memory.creates.length=0;await assert.rejects(createTenantBootstrapTransactionStore(memory).execute(aggregate()),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(memory.creates.length,0);assert.equal(memory.docs.get(path)?.actorUid,"other")});
