import assert from "node:assert/strict";
import test from "node:test";
import { PLATFORM_AUTHORITY_REGISTRY_STATES as RS, PLATFORM_AUTHORITY_STATUSES as AS } from "@mipymetic/saas-contracts/authority";
import { platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath } from "@mipymetic/saas-contracts/persistence";
import { BACKEND_ERROR_CODES } from "@mipymetic/saas-contracts/errors";
import type { AuthorityResolution, JsonValue } from "../contracts/types.js";
import { BackendError } from "../errors/backendError.js";
import { executeBootstrapPlatformAdmins, validateBootstrapPlatformAdminsInput, type BootstrapAuthPort, type BootstrapAuthUser, type BootstrapDependencies, type BootstrapPlatformAdminsInput } from "../commands/bootstrapPlatformAdmins.js";
import { createPlatformCommandTransactionStore } from "../persistence/platformCommandTransactionStore.js";
import { isServerOwnedTimestamp, type AuthoritativeReaderPort, type DocumentSnapshotPort, type TransactionPort, type TransactionRunnerPort } from "../persistence/ports.js";

const now="2026-01-01T00:00:00.000Z", operator:AuthorityResolution=Object.freeze({actorUid:"bootstrap-job",actorType:"system",authority:"platform_system",tenantId:null,roles:Object.freeze([]),capabilities:Object.freeze([])});
const input=():BootstrapPlatformAdminsInput=>({commandId:"bootstrap-1",correlationId:"correlation-1",environment:"local",confirmationId:"confirmation-1",targets:[{uid:"admin-a",expectedNormalizedEmail:"a@example.com"},{uid:"admin-b",expectedNormalizedEmail:"b@example.com"}]});
const registry=()=>({schemaVersion:1,bootstrapState:RS.UNINITIALIZED,activeCount:0,revision:0,lastCommandId:null,updatedAt:now});
const logical=(value:unknown):unknown=>isServerOwnedTimestamp(value)?now:Array.isArray(value)?value.map(logical):value!==null&&typeof value==="object"&&Object.getPrototypeOf(value)===Object.prototype?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,logical(v)])):value;
class Memory implements TransactionPort,TransactionRunnerPort,AuthoritativeReaderPort{readonly docs=new Map<string,Readonly<Record<string,JsonValue>>>();async run<T>(operation:(transaction:TransactionPort)=>Promise<T>){return operation(this)}async get(path:string){const data=this.docs.get(path)??null;return {exists:data!==null,data} as DocumentSnapshotPort}async read(path:string){return this.get(path)}create(path:string,data:Readonly<Record<string,unknown>>){if(this.docs.has(path))throw new Error("already exists");this.docs.set(path,logical(data) as Readonly<Record<string,JsonValue>>)}set(path:string,data:Readonly<Record<string,unknown>>){this.docs.set(path,logical(data) as Readonly<Record<string,JsonValue>>)}update(path:string,data:Readonly<Record<string,unknown>>){this.docs.set(path,{...(this.docs.get(path)??{}),...logical(data) as object} as Readonly<Record<string,JsonValue>>)}}
class Auth implements BootstrapAuthPort{readonly writes:string[]=[];readonly users=new Map<string,BootstrapAuthUser>([["admin-a",{uid:"admin-a",email:"a@example.com",emailVerified:true,disabled:false,customClaims:{theme:"dark"}}],["admin-b",{uid:"admin-b",email:"b@example.com",emailVerified:true,disabled:false,customClaims:{}}]]);failUid:string|null=null;async getUser(uid:string){const user=this.users.get(uid);if(!user)throw Object.assign(new Error("missing"),{code:"auth/user-not-found"});return Object.freeze({...user,customClaims:Object.freeze({...user.customClaims})})}async setCustomClaims(uid:string,claims:Readonly<Record<string,JsonValue>>){if(this.failUid===uid)throw Object.assign(new Error("down"),{code:"auth/internal-error"});const current=this.users.get(uid);if(!current)throw new Error("missing");this.writes.push(uid);this.users.set(uid,{...current,customClaims:{...claims}})}}
const deps=()=>{const memory=new Memory();memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());const auth=new Auth();const dependencies:BootstrapDependencies={runner:memory,store:createPlatformCommandTransactionStore(memory),approval:{verify:async()=>true},auth,identity:{verify:async()=>undefined},operator};return {memory,auth,dependencies}};

test("Bootstrap input is exact, closed and requires two distinct normalized targets",()=>{assert.deepEqual(validateBootstrapPlatformAdminsInput(input()),input());for(const bad of [{...input(),commandId:"a/b"},{...input(),correlationId:" "},{...input(),confirmationId:"."},{...input(),targets:[input().targets[0]]},{...input(),targets:[...input().targets,{uid:"admin-c",expectedNormalizedEmail:"c@example.com"}]},{...input(),targets:[input().targets[0],input().targets[0]]},{...input(),targets:[{uid:"admin-a",expectedNormalizedEmail:"A@example.com"},input().targets[1]]},{...input(),actorUid:"spoof"},{...input(),capabilities:[]},{...input(),timestamp:now}])assert.throws(()=>validateBootstrapPlatformAdminsInput(bad),BackendError)});
test("approval fails before command, Authority or Auth effects",async()=>{const {memory,auth,dependencies}=deps();dependencies.approval.verify=async()=>false;await assert.rejects(executeBootstrapPlatformAdmins(input(),dependencies),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.FORBIDDEN);assert.equal(memory.docs.has(privilegedCommandDocumentPath("bootstrap-1")),false);assert.equal(auth.writes.length,0)});
test("Identity and Auth eligibility fail before prepare",async()=>{for(const mutate of [(dependencies:BootstrapDependencies)=>{dependencies.identity.verify=async()=>{throw new BackendError(BACKEND_ERROR_CODES.FAILED_PRECONDITION,"bad Identity")}},(_dependencies:BootstrapDependencies,auth:Auth)=>{auth.users.set("admin-a",{...auth.users.get("admin-a")!,disabled:true})},(_dependencies:BootstrapDependencies,auth:Auth)=>{auth.users.set("admin-a",{...auth.users.get("admin-a")!,emailVerified:false})},(_dependencies:BootstrapDependencies,auth:Auth)=>{auth.users.set("admin-a",{...auth.users.get("admin-a")!,email:"other@example.com"})}]){const {memory,auth,dependencies}=deps();mutate(dependencies,auth);await assert.rejects(executeBootstrapPlatformAdmins(input(),dependencies),BackendError);assert.equal(memory.docs.has(privilegedCommandDocumentPath("bootstrap-1")),false);assert.equal(auth.writes.length,0)}});
test("Bootstrap prepares, preserves claims, verifies and finalizes exactly once",async()=>{const {memory,auth,dependencies}=deps();const first=await executeBootstrapPlatformAdmins(input(),dependencies);assert.equal(first.replayed,false);assert.deepEqual(auth.users.get("admin-a")?.customClaims,{theme:"dark",platformRole:"platform_admin"});assert.equal(auth.writes.length,2);const reg=memory.docs.get(platformAuthorityRegistryDocumentPath());assert.equal(reg?.bootstrapState,RS.COMPLETED);assert.equal(reg?.activeCount,2);assert.equal(reg?.revision,2);for(const uid of ["admin-a","admin-b"]){const authority=memory.docs.get(platformAuthorityDocumentPath(uid));assert.equal(authority?.status,AS.ACTIVE);assert.equal(authority?.transitionCommandId,null);assert.equal(authority?.bootstrapCommandId,"bootstrap-1");assert.equal(authority?.lastClaimSyncAt,now)}const command=memory.docs.get(privilegedCommandDocumentPath("bootstrap-1"));assert.equal(command?.status,"succeeded");assert.equal(command?.stage,"completed");const writes=auth.writes.length,revision=reg?.revision;const replay=await executeBootstrapPlatformAdmins(input(),dependencies);assert.equal(replay.replayed,true);assert.equal(auth.writes.length,writes);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.revision,revision)});
test("unexpected claim fails closed and persists recovery_required",async()=>{const {memory,auth,dependencies}=deps();auth.users.set("admin-b",{...auth.users.get("admin-b")!,customClaims:{platformRole:"other"}});await assert.rejects(executeBootstrapPlatformAdmins(input(),dependencies),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.bootstrapState,RS.RECOVERY_REQUIRED);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,0);for(const uid of ["admin-a","admin-b"]){assert.equal(memory.docs.get(platformAuthorityDocumentPath(uid))?.status,AS.RECOVERY_REQUIRED);assert.equal(memory.docs.get(platformAuthorityDocumentPath(uid))?.transitionCommandId,"bootstrap-1")}});
test("A success and B failure retains A claim and resumes forward",async()=>{const {memory,auth,dependencies}=deps();auth.failUid="admin-b";await assert.rejects(executeBootstrapPlatformAdmins(input(),dependencies),BackendError);assert.equal(auth.users.get("admin-a")?.customClaims.platformRole,"platform_admin");assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,0);auth.failUid=null;const completed=await executeBootstrapPlatformAdmins(input(),dependencies);assert.equal(completed.replayed,false);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,2)});
test("payload and correlation conflicts never replay",async()=>{const {dependencies}=deps();await executeBootstrapPlatformAdmins(input(),dependencies);await assert.rejects(executeBootstrapPlatformAdmins({...input(),correlationId:"different"},dependencies),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONFLICT);await assert.rejects(executeBootstrapPlatformAdmins({...input(),confirmationId:"different"},dependencies),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONFLICT)});
