import assert from "node:assert/strict";
import test from "node:test";
import { PLATFORM_AUTHORITY_SCHEMA_VERSION, PLATFORM_AUTHORITY_REGISTRY_STATES as RS, PLATFORM_AUTHORITY_STATUSES as AS } from "@mipymetic/saas-contracts/authority";
import { COMMAND_SCHEMA_VERSION, COMMAND_STATUSES as CS, COMMAND_TYPES, PRIVILEGED_COMMAND_STAGES as ST } from "@mipymetic/saas-contracts/commands";
import { BACKEND_ERROR_CODES } from "@mipymetic/saas-contracts/errors";
import { platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath } from "@mipymetic/saas-contracts/persistence";
import type { AuthorityResolution, CommandRecord, JsonValue } from "../contracts/types.js";
import { BackendError } from "../errors/backendError.js";
import { createPlatformCommandTransactionStore, type PlatformCommandStoreMutation } from "../persistence/platformCommandTransactionStore.js";
import { isServerOwnedTimestamp, type DocumentSnapshotPort, type TransactionPort, type TransactionRunnerPort } from "../persistence/ports.js";
import { externalEffect } from "../persistence/transactionBoundary.js";

const now="2026-01-01T00:00:00.000Z";
const actor:AuthorityResolution=Object.freeze({actorUid:"actor-1",actorType:"platform_admin",authority:"platform_admin",tenantId:null,roles:Object.freeze(["platform_admin"]),capabilities:Object.freeze([])});
const command=(type:string=COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,id="command-1"):CommandRecord=>Object.freeze({commandId:id,commandType:type,payloadHash:"a".repeat(64),actorUid:actor.actorUid,actorType:actor.actorType,authority:actor.authority,tenantId:null,status:CS.PENDING,stage:ST.NOT_STARTED,startedAt:now,completedAt:null,failedAt:null,result:null,errorCode:null,attemptCount:0,correlationId:`correlation-${id}`,expiresAt:null,leaseExpiresAt:null,schemaVersion:COMMAND_SCHEMA_VERSION});
const registry=(count=0,state:string=RS.UNINITIALIZED,revision=0,last:string|null=null)=>({schemaVersion:1,bootstrapState:state,activeCount:count,revision,lastCommandId:last,updatedAt:now});
const authority=(uid:string,status:string=AS.ACTIVE,owner:string|null=null)=>({schemaVersion:PLATFORM_AUTHORITY_SCHEMA_VERSION,transitionCommandId:owner,uid,authority:"platform_admin",status,createdAt:now,createdBy:"command-0",updatedAt:now,updatedBy:"command-0",activatedAt:status===AS.ACTIVE?now:null,revokedAt:null,revokedBy:null,bootstrapCommandId:null,lastClaimSyncAt:null});
const snap=(data:Readonly<Record<string,JsonValue>>|null):DocumentSnapshotPort=>({exists:data!==null,data});
class Tx implements TransactionPort{readonly writes:Array<{method:string;path:string;data:Readonly<Record<string,unknown>>}>=[];constructor(readonly values:Map<string,DocumentSnapshotPort>){} async get(path:string){return this.values.get(path)??snap(null)} create(path:string,data:Readonly<Record<string,unknown>>){this.writes.push({method:"create",path,data})} set(path:string,data:Readonly<Record<string,unknown>>){this.writes.push({method:"set",path,data})} update(path:string,data:Readonly<Record<string,unknown>>){this.writes.push({method:"update",path,data})}}
class Runner implements TransactionRunnerPort{constructor(readonly tx:Tx){} async run<T>(operation:(tx:TransactionPort)=>Promise<T>){return operation(this.tx)}}
const values=(cmd=command(),reg=registry(),auths:readonly Readonly<Record<string,JsonValue>>[]=[])=>new Map<string,DocumentSnapshotPort>([[privilegedCommandDocumentPath(cmd.commandId),snap(cmd)],[platformAuthorityRegistryDocumentPath(),snap(reg)],...auths.map(a=>[platformAuthorityDocumentPath(String(a.uid)),snap(a)] as const)]);
const mutation=(over:Partial<PlatformCommandStoreMutation>={}):PlatformCommandStoreMutation=>({commandId:"command-1",correlationId:"correlation-command-1",payloadHash:"a".repeat(64),nextCommandStatus:CS.RUNNING,nextCommandStage:ST.PREPARED,commandResult:null,commandErrorCode:null,nextRegistryState:RS.IN_PROGRESS,activeCountDelta:0,authorities:[{uid:"admin-a",expectedStatus:null,nextStatus:AS.PROVISIONING,bootstrapCommandId:"command-1"},{uid:"admin-b",expectedStatus:null,nextStatus:AS.PROVISIONING,bootstrapCommandId:"command-1"}],audit:{auditId:"audit-1",authority:actor,operation:"BootstrapPlatformAdmins.prepare",resourceType:"platform_authority_registry",resourceId:"authorityRegistry",result:"succeeded",errorCode:null,beforeSummary:{},afterSummary:{},metadata:{stage:"prepare"}},...over});

test("bootstrap prepare owns both authorities and advances Registry once atomically",async()=>{const tx=new Tx(values());const result=await createPlatformCommandTransactionStore(new Runner(tx)).mutate(mutation());assert.equal(result.registry.revision,1);assert.equal(result.registry.activeCount,0);assert.equal(result.registry.lastCommandId,"command-1");assert.ok(result.authorities.every(a=>a.transitionCommandId==="command-1"));assert.equal(tx.writes.length,5);assert.ok(tx.writes.flatMap(w=>Object.values(w.data)).some(isServerOwnedTimestamp));});
test("malformed Registry, Authority and Command fail before writes",async()=>{const cases=[[privilegedCommandDocumentPath("command-1"),{}],[platformAuthorityRegistryDocumentPath(),{...registry(),revision:-1}],[platformAuthorityDocumentPath("admin-a"),{...authority("admin-a"),status:"bad"}]] as const;for(const [path,bad] of cases){const map=values(command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN),registry(1,RS.COMPLETED,1,"old"),[authority("admin-a",AS.RECOVERY_REQUIRED,"command-1")]);map.set(path,snap(bad));const tx=new Tx(map);await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).mutate(mutation({nextRegistryState:RS.COMPLETED,authorities:[{uid:"admin-a",expectedStatus:AS.RECOVERY_REQUIRED,nextStatus:AS.PROVISIONING,bootstrapCommandId:null}]})),BackendError);assert.equal(tx.writes.length,0)}});
test("payload, correlation and foreign ownership conflict",async()=>{for(const over of [{payloadHash:"b".repeat(64)},{correlationId:"different"}]){const tx=new Tx(values());await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).mutate(mutation(over)),(e:unknown)=>e instanceof BackendError&&e.code===BACKEND_ERROR_CODES.CONFLICT);assert.equal(tx.writes.length,0)}const tx=new Tx(values(command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN),registry(1,RS.COMPLETED,1,"old"),[authority("admin-a",AS.RECOVERY_REQUIRED,"other")]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).mutate(mutation({nextRegistryState:RS.COMPLETED,authorities:[{uid:"admin-a",expectedStatus:AS.RECOVERY_REQUIRED,nextStatus:AS.PROVISIONING,bootstrapCommandId:null}]})),(e:unknown)=>e instanceof BackendError&&e.code===BACKEND_ERROR_CODES.CONFLICT)});
test("same-owner recovery resume keeps count and clears owner only on active",async()=>{const cmd={...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN),status:CS.RECOVERY_REQUIRED,stage:ST.PREPARED};const tx=new Tx(values(cmd,registry(1,RS.RECOVERY_REQUIRED,3,"command-1"),[authority("admin-a",AS.RECOVERY_REQUIRED,"command-1")]));const result=await createPlatformCommandTransactionStore(new Runner(tx)).mutate(mutation({nextCommandStatus:CS.RUNNING,nextCommandStage:ST.PREPARED,nextRegistryState:RS.IN_PROGRESS,authorities:[{uid:"admin-a",expectedStatus:AS.RECOVERY_REQUIRED,nextStatus:AS.PROVISIONING,bootstrapCommandId:null}]}));assert.equal(result.registry.activeCount,1);assert.equal(result.registry.revision,4);assert.equal(result.authorities[0]?.transitionCommandId,"command-1")});
test("revoke decrements once and last-admin rejects",async()=>{const cmd=command(COMMAND_TYPES.REVOKE_PLATFORM_ADMIN);const first=new Tx(values(cmd,registry(2,RS.COMPLETED,5,"old"),[authority("admin-a")]));const input=mutation({activeCountDelta:-1,nextRegistryState:RS.COMPLETED,authorities:[{uid:"admin-a",expectedStatus:AS.ACTIVE,nextStatus:AS.REVOKING,bootstrapCommandId:null}]});assert.equal((await createPlatformCommandTransactionStore(new Runner(first)).mutate(input)).registry.activeCount,1);const second=new Tx(values(cmd,registry(1,RS.COMPLETED,6,"command-1"),[authority("admin-b")]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(second)).mutate(mutation({...input,authorities:[{uid:"admin-b",expectedStatus:AS.ACTIVE,nextStatus:AS.REVOKING,bootstrapCommandId:null}]})),(e:unknown)=>e instanceof BackendError&&e.code===BACKEND_ERROR_CODES.FAILED_PRECONDITION);assert.equal(second.writes.length,0)});
test("stage skipping/backtracking and external effects fail closed",async()=>{const prepared={...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN),status:CS.RUNNING,stage:ST.PREPARED};for(const stage of [ST.NOT_STARTED,ST.COMPLETED]){const tx=new Tx(values(prepared,registry(1,RS.IN_PROGRESS,1,"command-1")));await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).mutate(mutation({nextCommandStage:stage,nextRegistryState:RS.IN_PROGRESS,authorities:[]})),BackendError);assert.equal(tx.writes.length,0)}await assert.rejects(externalEffect(),BackendError)});

const recoveryAudit=(id:string,operation="RecoverPlatformAdmin.prepare")=>({auditId:`audit-${id}`,authority:actor,operation,resourceType:"platform_authority",resourceId:"admin-a",result:"succeeded" as const,errorCode:null,beforeSummary:{},afterSummary:{},metadata:{stage:"prepare"}});
test("active Recovery ownership claim is atomic, count-neutral and same-owner idempotent",async()=>{const cmd=command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-1"),tx=new Tx(values(cmd,registry(2,RS.COMPLETED,4,"old"),[authority("admin-a")]));const store=createPlatformCommandTransactionStore(new Runner(tx)),request={commandId:"recover-1",correlationId:"correlation-recover-1",payloadHash:"a".repeat(64),targetUid:"admin-a",audit:recoveryAudit("recover-1")};const claimed=await store.claimActiveRecoveryOwnership(request);assert.equal(claimed.authorities[0]?.status,AS.ACTIVE);assert.equal(claimed.authorities[0]?.transitionCommandId,"recover-1");assert.equal(claimed.registry.activeCount,2);assert.equal(claimed.registry.revision,5);assert.equal(claimed.registry.lastCommandId,"recover-1");assert.equal(claimed.command.status,CS.RUNNING);assert.equal(claimed.command.stage,ST.PREPARED);const persisted={...cmd,status:CS.RUNNING,stage:ST.PREPARED},owned=authority("admin-a",AS.ACTIVE,"recover-1"),retryTx=new Tx(values(persisted,registry(2,RS.IN_PROGRESS,5,"recover-1"),[owned]));const retried=await createPlatformCommandTransactionStore(new Runner(retryTx)).claimActiveRecoveryOwnership(request);assert.equal(retried.registry.revision,5);assert.equal(retryTx.writes.length,0)});
test("active Recovery ownership rejects a foreign owner",async()=>{const tx=new Tx(values(command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-2"),registry(2,RS.IN_PROGRESS,5,"recover-1"),[authority("admin-a",AS.ACTIVE,"recover-1")]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).claimActiveRecoveryOwnership({commandId:"recover-2",correlationId:"correlation-recover-2",payloadHash:"a".repeat(64),targetUid:"admin-a",audit:recoveryAudit("recover-2")}),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONFLICT);assert.equal(tx.writes.length,0)});
test("active Recovery ownership rejects every non-active same-owner lifecycle",async()=>{const request={commandId:"recover-1",correlationId:"correlation-recover-1",payloadHash:"a".repeat(64),targetUid:"admin-a",audit:recoveryAudit("recover-1")},prepared={...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-1"),status:CS.RUNNING,stage:ST.PREPARED};for(const status of [AS.PROVISIONING,AS.REVOKING,AS.RECOVERY_REQUIRED]){const tx=new Tx(values(prepared,registry(2,RS.IN_PROGRESS,5,"recover-1"),[authority("admin-a",status,"recover-1")]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).claimActiveRecoveryOwnership(request),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.FAILED_PRECONDITION);assert.equal(tx.writes.length,0)}const revoked={...authority("admin-a",AS.REVOKED,null),transitionCommandId:"recover-1"},tx=new Tx(values(prepared,registry(2,RS.IN_PROGRESS,5,"recover-1"),[revoked]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).claimActiveRecoveryOwnership(request),BackendError);assert.equal(tx.writes.length,0)});
test("active Recovery ownership rejects wrong command lifecycle and binding",async()=>{const request={commandId:"recover-1",correlationId:"correlation-recover-1",payloadHash:"a".repeat(64),targetUid:"admin-a",audit:recoveryAudit("recover-1")};for(const cmd of [command(COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,"recover-1"),{...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-1"),status:CS.SUCCEEDED,stage:ST.COMPLETED},{...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-1"),status:CS.RUNNING,stage:ST.NOT_STARTED}]){const tx=new Tx(values(cmd,registry(2,RS.COMPLETED,5,"old"),[authority("admin-a")]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).claimActiveRecoveryOwnership(request),BackendError);assert.equal(tx.writes.length,0)}for(const changed of [{...request,correlationId:"different"},{...request,payloadHash:"b".repeat(64)}]){const tx=new Tx(values(command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-1"),registry(2,RS.COMPLETED,5,"old"),[authority("admin-a")]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).claimActiveRecoveryOwnership(changed),BackendError);assert.equal(tx.writes.length,0)}});
test("authorized handoff accepts only prior Recover recovery_required/prepared and preserves history",async()=>{const prior={...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-old"),status:CS.RECOVERY_REQUIRED,stage:ST.PREPARED},next=command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-new"),map=values(next,registry(1,RS.RECOVERY_REQUIRED,7,"recover-old"),[authority("admin-a",AS.RECOVERY_REQUIRED,"recover-old")]);map.set(privilegedCommandDocumentPath("recover-old"),snap(prior));const tx=new Tx(map),result=await createPlatformCommandTransactionStore(new Runner(tx)).handoffRecoveryOwnership({commandId:"recover-new",correlationId:"correlation-recover-new",payloadHash:"a".repeat(64),targetUid:"admin-a",priorCommandId:"recover-old",audit:recoveryAudit("recover-new","RecoverPlatformAdmin.ownership_handoff")});assert.equal(result.authorities[0]?.status,AS.PROVISIONING);assert.equal(result.authorities[0]?.transitionCommandId,"recover-new");assert.equal(result.registry.activeCount,1);assert.equal(result.registry.revision,8);assert.equal(tx.writes.some(write=>write.path===privilegedCommandDocumentPath("recover-old")),false)});
test("handoff rejects Bootstrap, Revoke, live, malformed and missing prior owners",async()=>{for(const prior of [command(COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,"prior"),command(COMMAND_TYPES.REVOKE_PLATFORM_ADMIN,"prior"),{...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"prior"),status:CS.RUNNING,stage:ST.PREPARED},{}]){const map=values(command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-new"),registry(1,RS.RECOVERY_REQUIRED,7,"prior"),[authority("admin-a",AS.RECOVERY_REQUIRED,"prior")]);map.set(privilegedCommandDocumentPath("prior"),snap(prior as Readonly<Record<string,JsonValue>>));const tx=new Tx(map);await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).handoffRecoveryOwnership({commandId:"recover-new",correlationId:"correlation-recover-new",payloadHash:"a".repeat(64),targetUid:"admin-a",priorCommandId:"prior",audit:recoveryAudit("recover-new")}),BackendError);assert.equal(tx.writes.length,0)}const map=values(command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-new"),registry(1,RS.RECOVERY_REQUIRED,7,"prior"),[authority("admin-a",AS.RECOVERY_REQUIRED,"prior")]),tx=new Tx(map);await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).handoffRecoveryOwnership({commandId:"recover-new",correlationId:"correlation-recover-new",payloadHash:"a".repeat(64),targetUid:"admin-a",priorCommandId:"prior",audit:recoveryAudit("recover-new")}),BackendError)});
test("generic mutate rejects the retired active-owner flag for every command type",async()=>{for(const type of Object.values(COMMAND_TYPES)){const cmd=command(type),reg=type===COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS?registry(0,RS.UNINITIALIZED,0,null):registry(2,RS.COMPLETED,4,"old"),tx=new Tx(values(cmd,reg,[authority("admin-a") ])),lookalike=mutation({authorities:[{uid:"admin-a",expectedStatus:AS.ACTIVE,nextStatus:AS.ACTIVE,bootstrapCommandId:null,retainTransitionOwner:true}] as unknown as PlatformCommandStoreMutation["authorities"],activeCountDelta:type===COMMAND_TYPES.REVOKE_PLATFORM_ADMIN?-1:0,nextCommandStatus:CS.RUNNING,nextCommandStage:ST.PREPARED,nextRegistryState:RS.IN_PROGRESS});await assert.rejects(createPlatformCommandTransactionStore(new Runner(tx)).mutate(lookalike),(error:unknown)=>error instanceof BackendError&&error.code===BACKEND_ERROR_CODES.CONTRACT_VIOLATION);assert.equal(tx.writes.length,0)}});
test("active Recovery failure checkpoint is narrow and same-owner idempotent",async()=>{const running={...command(COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"recover-fail"),status:CS.RUNNING,stage:ST.PREPARED},owned=authority("admin-a",AS.ACTIVE,"recover-fail"),tx=new Tx(values(running,registry(2,RS.IN_PROGRESS,8,"recover-fail"),[owned])),store=createPlatformCommandTransactionStore(new Runner(tx)),request={commandId:"recover-fail",correlationId:"correlation-recover-fail",payloadHash:"a".repeat(64),targetUid:"admin-a",audit:{...recoveryAudit("recover-fail"),result:"recovery_required" as const}};const result=await store.markActiveRecoveryRequired(request);assert.equal(result.command.status,CS.RECOVERY_REQUIRED);assert.equal(result.authorities[0]?.status,AS.ACTIVE);assert.equal(result.authorities[0]?.transitionCommandId,"recover-fail");assert.equal(result.registry.activeCount,2);assert.equal(result.registry.revision,9);for(const invalid of [{...running,status:CS.PENDING,stage:ST.NOT_STARTED},{...running,status:CS.SUCCEEDED,stage:ST.COMPLETED}]){const invalidTx=new Tx(values(invalid,registry(2,RS.IN_PROGRESS,8,"recover-fail"),[owned]));await assert.rejects(createPlatformCommandTransactionStore(new Runner(invalidTx)).markActiveRecoveryRequired(request),BackendError);assert.equal(invalidTx.writes.length,0)}const retryCommand={...running,status:CS.RECOVERY_REQUIRED},retryTx=new Tx(values(retryCommand,registry(2,RS.RECOVERY_REQUIRED,9,"recover-fail"),[owned]));await createPlatformCommandTransactionStore(new Runner(retryTx)).markActiveRecoveryRequired(request);assert.equal(retryTx.writes.length,0)});
