import assert from "node:assert/strict";
import test from "node:test";
import { PLATFORM_AUTHORITY_SCHEMA_VERSION, PLATFORM_AUTHORITY_REGISTRY_STATES as RS, PLATFORM_AUTHORITY_STATUSES as AS } from "@mipymetic/saas-contracts/authority";
import { COMMAND_SCHEMA_VERSION, COMMAND_STATUSES as CS, COMMAND_TYPES, PRIVILEGED_COMMAND_STAGES as ST } from "@mipymetic/saas-contracts/commands";
import { BACKEND_ERROR_CODES as EC } from "@mipymetic/saas-contracts/errors";
import { identityDocumentPath, platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath } from "@mipymetic/saas-contracts/persistence";
import type { AuthorityResolution, JsonValue } from "../contracts/types.js";
import { createFirestoreBootstrapIdentityPort, type BootstrapAuthPort, type BootstrapAuthUser } from "../commands/bootstrapPlatformAdmins.js";
import { executeRecoverPlatformAdmin, validateRecoverPlatformAdminInput, type RecoverDependencies, type RecoverPlatformAdminInput } from "../commands/recoverPlatformAdmin.js";
import { BackendError } from "../errors/backendError.js";
import { createPlatformCommandTransactionStore } from "../persistence/platformCommandTransactionStore.js";
import { isServerOwnedTimestamp, type AuthoritativeReaderPort, type DocumentSnapshotPort, type TransactionPort, type TransactionRunnerPort } from "../persistence/ports.js";

const now="2026-01-01T00:00:00.000Z",operator:AuthorityResolution=Object.freeze({actorUid:"recovery-job",actorType:"system",authority:"platform_recovery",tenantId:null,roles:Object.freeze([]),capabilities:Object.freeze([])});
const input=(id="recover-1"):RecoverPlatformAdminInput=>({commandId:id,correlationId:`correlation-${id}`,environment:"local",projectId:"project-local",confirmationId:`confirmation-${id}`,target:{uid:"admin-a",expectedNormalizedEmail:"a@example.com"}});
const registry=(count=1,state:string=RS.COMPLETED,revision=1,last:string|null="bootstrap-1")=>({schemaVersion:1,bootstrapState:state,activeCount:count,revision,lastCommandId:last,updatedAt:now});
const identity=()=>({uid:"admin-a",email:"a@example.com",displayName:"Admin",photoURL:null,emailVerified:true,interfaceLocale:"en",createdAt:now,updatedAt:now});
const authority=(status:string=AS.ACTIVE,owner:string|null=null)=>({schemaVersion:PLATFORM_AUTHORITY_SCHEMA_VERSION,transitionCommandId:owner,uid:"admin-a",authority:"platform_admin",status,createdAt:now,createdBy:"bootstrap",updatedAt:now,updatedBy:"bootstrap",activatedAt:status===AS.ACTIVE?now:null,revokedAt:null,revokedBy:null,bootstrapCommandId:"bootstrap-1",lastClaimSyncAt:null});
const command=(id:string,type:string=COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,status:string=CS.RECOVERY_REQUIRED,stage:string=ST.PREPARED)=>({commandId:id,commandType:type,payloadHash:"a".repeat(64),actorUid:"recovery-job",actorType:"system",authority:"platform_recovery",tenantId:null,status,stage,startedAt:now,completedAt:null,failedAt:null,result:null,errorCode:null,attemptCount:0,correlationId:`correlation-${id}`,expiresAt:null,leaseExpiresAt:null,schemaVersion:COMMAND_SCHEMA_VERSION});
const logical=(v:unknown):unknown=>isServerOwnedTimestamp(v)?now:Array.isArray(v)?v.map(logical):v!==null&&typeof v==="object"&&Object.getPrototypeOf(v)===Object.prototype?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,logical(x)])):v;
class Memory implements TransactionPort,TransactionRunnerPort,AuthoritativeReaderPort{readonly docs=new Map<string,Readonly<Record<string,JsonValue>>>();readonly writes:string[]=[];async run<T>(op:(tx:TransactionPort)=>Promise<T>){return op(this)}async get(path:string){const data=this.docs.get(path)??null;return {exists:data!==null,data} as DocumentSnapshotPort}async read(path:string){return this.get(path)}create(path:string,data:Readonly<Record<string,unknown>>){this.writes.push(path);this.docs.set(path,logical(data) as Readonly<Record<string,JsonValue>>)}set(path:string,data:Readonly<Record<string,unknown>>){this.writes.push(path);this.docs.set(path,logical(data) as Readonly<Record<string,JsonValue>>)}update(path:string,data:Readonly<Record<string,unknown>>){this.writes.push(path);this.docs.set(path,{...(this.docs.get(path)??{}),...logical(data) as object} as Readonly<Record<string,JsonValue>>)}}
class Auth implements BootstrapAuthPort{readonly writes:string[]=[];readonly user:BootstrapAuthUser={uid:"admin-a",email:"a@example.com",emailVerified:true,disabled:false,customClaims:{theme:"dark"}};current={...this.user,customClaims:{...this.user.customClaims}};fail=false;async getUser(){return Object.freeze({...this.current,customClaims:Object.freeze({...this.current.customClaims})})}async setCustomClaims(uid:string,claims:Readonly<Record<string,JsonValue>>){if(this.fail)throw Object.assign(new Error("down"),{code:"auth/internal-error"});this.writes.push(uid);this.current={...this.current,customClaims:{...claims}}}}
const setup=(a=authority())=>{const memory=new Memory(),auth=new Auth();memory.docs.set(platformAuthorityRegistryDocumentPath(),registry());memory.docs.set(platformAuthorityDocumentPath("admin-a"),a);memory.docs.set(identityDocumentPath("admin-a"),identity());const deps:RecoverDependencies={runner:memory,reader:memory,store:createPlatformCommandTransactionStore(memory),approval:{verify:async()=>true},auth,identity:createFirestoreBootstrapIdentityPort(memory),operator};return {memory,auth,deps}};

test("Recover payload is exact, closed and validates every identifier",()=>{assert.deepEqual(validateRecoverPlatformAdminInput(input()),input());for(const bad of [{...input(),commandId:""},{...input(),correlationId:" "},{...input(),projectId:"."},{...input(),confirmationId:".."},{...input(),target:{...input().target,uid:"a/b"}},{...input(),actorUid:"spoof"},{...input(),target:[input().target]}])assert.throws(()=>validateRecoverPlatformAdminInput(bad),BackendError)});
test("approval, Auth and Identity fail before persistence",async()=>{for(const kind of ["approval","auth","identity"]){const {memory,auth,deps}=setup();if(kind==="auth")auth.current={...auth.current,disabled:true};const candidate:RecoverDependencies=kind==="approval"?{...deps,approval:{verify:async()=>false}}:kind==="identity"?{...deps,identity:{verify:async()=>{throw new BackendError(EC.CONTRACT_VIOLATION,"bad")}}}:deps;await assert.rejects(executeRecoverPlatformAdmin(input(),candidate),BackendError);assert.equal(memory.docs.has(privilegedCommandDocumentPath("recover-1")),false);assert.equal(auth.writes.length,0)}});
test("active recovery owns, preserves claims, finalizes count-neutral and replays read-only",async()=>{const {memory,auth,deps}=setup();const first=await executeRecoverPlatformAdmin(input(),deps);assert.equal(first.replayed,false);assert.deepEqual(auth.current.customClaims,{theme:"dark",platformRole:"platform_admin"});assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,1);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-a"))?.transitionCommandId,null);const writes=memory.writes.length,authWrites=auth.writes.length,replay=await executeRecoverPlatformAdmin(input(),deps);assert.equal(replay.replayed,true);assert.equal(memory.writes.length,writes);assert.equal(auth.writes.length,authWrites)});
test("unexpected claim fails closed in active recovery and retains active owner",async()=>{const {memory,auth,deps}=setup();auth.current={...auth.current,customClaims:{platformRole:"student"}};await assert.rejects(executeRecoverPlatformAdmin(input(),deps),(e:unknown)=>e instanceof BackendError&&e.code===EC.CONTRACT_VIOLATION);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-a"))?.status,AS.ACTIVE);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-a"))?.transitionCommandId,"recover-1");assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,1);assert.equal(memory.docs.get(privilegedCommandDocumentPath("recover-1"))?.status,CS.RECOVERY_REQUIRED)});
test("eligible prior Recover handoff activates once and preserves prior command",async()=>{const {memory,deps}=setup(authority(AS.RECOVERY_REQUIRED,"recover-old"));memory.docs.set(platformAuthorityRegistryDocumentPath(),registry(0,RS.RECOVERY_REQUIRED,3,"recover-old"));const prior=command("recover-old");memory.docs.set(privilegedCommandDocumentPath("recover-old"),prior);await executeRecoverPlatformAdmin(input("recover-new"),deps);assert.deepEqual(memory.docs.get(privilegedCommandDocumentPath("recover-old")),prior);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,1);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-a"))?.status,AS.ACTIVE)});
test("Bootstrap, Revoke and live Recover owners cannot handoff",async()=>{for(const prior of [command("prior",COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS),command("prior",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN),command("prior",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,CS.RUNNING,ST.PREPARED)]){const {memory,deps}=setup(authority(AS.RECOVERY_REQUIRED,"prior"));memory.docs.set(platformAuthorityRegistryDocumentPath(),registry(0,RS.RECOVERY_REQUIRED,3,"prior"));memory.docs.set(privilegedCommandDocumentPath("prior"),prior);await assert.rejects(executeRecoverPlatformAdmin(input("recover-new"),deps),BackendError);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-a"))?.transitionCommandId,"prior")}});
test("payload and correlation conflicts reject without replay",async()=>{const {deps}=setup();await executeRecoverPlatformAdmin(input(),deps);await assert.rejects(executeRecoverPlatformAdmin({...input(),correlationId:"different"},deps),(e:unknown)=>e instanceof BackendError&&e.code===EC.CONFLICT);await assert.rejects(executeRecoverPlatformAdmin({...input(),confirmationId:"different"},deps),(e:unknown)=>e instanceof BackendError&&e.code===EC.CONFLICT)});
