import assert from "node:assert/strict";
import test from "node:test";
import { PLATFORM_AUTHORITY_SCHEMA_VERSION,PLATFORM_AUTHORITY_REGISTRY_STATES as RS,PLATFORM_AUTHORITY_STATUSES as AS } from "@mipymetic/saas-contracts/authority";
import { BACKEND_ERROR_CODES as EC } from "@mipymetic/saas-contracts/errors";
import { identityDocumentPath,platformAuthorityDocumentPath,platformAuthorityRegistryDocumentPath,privilegedCommandDocumentPath } from "@mipymetic/saas-contracts/persistence";
import type { JsonValue } from "../contracts/types.js";
import { createFirestoreBootstrapIdentityPort,type BootstrapAuthPort,type BootstrapAuthUser } from "../commands/bootstrapPlatformAdmins.js";
import { executeRevokePlatformAdmin,validateRevokePlatformAdminInput,type RevokeDependencies } from "../commands/revokePlatformAdmin.js";
import { BackendError } from "../errors/backendError.js";
import { createPlatformCommandTransactionStore } from "../persistence/platformCommandTransactionStore.js";
import { isServerOwnedTimestamp,type AuthoritativeReaderPort,type DocumentSnapshotPort,type TransactionPort,type TransactionRunnerPort } from "../persistence/ports.js";

const now="2026-01-01T00:00:00.000Z";
const input=(id="revoke-1")=>({commandId:id,correlationId:`correlation-${id}`,targetUid:"admin-b"});
const registry=(count=2,state:string=RS.COMPLETED,revision=1)=>({schemaVersion:1,bootstrapState:state,activeCount:count,revision,lastCommandId:"bootstrap",updatedAt:now});
const identity=(uid:string)=>({uid,email:`${uid}@example.com`,displayName:uid,photoURL:null,emailVerified:true,interfaceLocale:"en",createdAt:now,updatedAt:now});
const authority=(uid:string,status:string=AS.ACTIVE,owner:string|null=null)=>({schemaVersion:PLATFORM_AUTHORITY_SCHEMA_VERSION,transitionCommandId:owner,uid,authority:"platform_admin",status,createdAt:now,createdBy:"bootstrap",updatedAt:now,updatedBy:"bootstrap",activatedAt:status===AS.ACTIVE?now:null,revokedAt:null,revokedBy:null,bootstrapCommandId:"bootstrap",lastClaimSyncAt:null});
const logical=(v:unknown):unknown=>isServerOwnedTimestamp(v)?now:Array.isArray(v)?v.map(logical):v!==null&&typeof v==="object"&&Object.getPrototypeOf(v)===Object.prototype?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,logical(x)])):v;
class Memory implements TransactionPort,TransactionRunnerPort,AuthoritativeReaderPort{
 readonly docs=new Map<string,Readonly<Record<string,JsonValue>>>();readonly writes:string[]=[];
 async run<T>(op:(tx:TransactionPort)=>Promise<T>){return op(this)} async get(path:string){const data=this.docs.get(path)??null;return{exists:data!==null,data} as DocumentSnapshotPort}async read(path:string){return this.get(path)}
 create(path:string,data:Readonly<Record<string,unknown>>){this.writes.push(path);this.docs.set(path,logical(data) as Readonly<Record<string,JsonValue>>)}set(path:string,data:Readonly<Record<string,unknown>>){this.writes.push(path);this.docs.set(path,logical(data) as Readonly<Record<string,JsonValue>>)}update(path:string,data:Readonly<Record<string,unknown>>){this.writes.push(path);this.docs.set(path,{...(this.docs.get(path)??{}),...logical(data) as object} as Readonly<Record<string,JsonValue>>)}
}
class Auth implements BootstrapAuthPort{
 readonly users=new Map<string,BootstrapAuthUser>([["admin-a",{uid:"admin-a",email:"admin-a@example.com",emailVerified:true,disabled:false,customClaims:{platformRole:"platform_admin"}}],["admin-b",{uid:"admin-b",email:"admin-b@example.com",emailVerified:true,disabled:false,customClaims:{theme:"dark",platformRole:"platform_admin"}}]]);readonly writes:string[]=[];fail=false;missing=false;
 async getUser(uid:string){if(this.missing&&uid==="admin-b")throw Object.assign(new Error("missing"),{code:"auth/user-not-found"});const u=this.users.get(uid);if(!u)throw Object.assign(new Error("missing"),{code:"auth/user-not-found"});return Object.freeze({...u,customClaims:Object.freeze({...u.customClaims})})}async setCustomClaims(uid:string,claims:Readonly<Record<string,JsonValue>>){if(this.fail)throw Object.assign(new Error("down"),{code:"auth/unavailable"});this.writes.push(uid);this.users.set(uid,{...this.users.get(uid)!,customClaims:{...claims}})}
}
const setup=(count=2,target=authority("admin-b"))=>{const memory=new Memory(),auth=new Auth();for(const uid of ["admin-a","admin-b"])memory.docs.set(identityDocumentPath(uid),identity(uid));memory.docs.set(platformAuthorityDocumentPath("admin-a"),authority("admin-a"));memory.docs.set(platformAuthorityDocumentPath("admin-b"),target);memory.docs.set(platformAuthorityRegistryDocumentPath(),registry(count));const deps:RevokeDependencies={authContext:{uid:"admin-a",token:{email_verified:true}},runner:memory,reader:memory,store:createPlatformCommandTransactionStore(memory),auth,identity:createFirestoreBootstrapIdentityPort(memory)};return{memory,auth,deps}};

test("Revoke payload is exact and closed",()=>{assert.deepEqual(validateRevokePlatformAdminInput(input()),input());for(const bad of [{...input(),commandId:""},{...input(),correlationId:" "},{...input(),targetUid:"a/b"},{...input(),actor:"x"},{commandId:"x",correlationId:"y"}])assert.throws(()=>validateRevokePlatformAdminInput(bad),BackendError)});
test("authentication, self revoke and last-admin fail without orphan command",async()=>{for(const context of [null,{uid:"admin-b"}]){const{memory,deps}=setup();await assert.rejects(executeRevokePlatformAdmin(input(),{...deps,authContext:context}),BackendError);assert.equal(memory.docs.has(privilegedCommandDocumentPath("revoke-1")),false)}for(const count of [0,1]){const{memory,auth,deps}=setup(count);const beforeAuthority=memory.docs.get(platformAuthorityDocumentPath("admin-b")),beforeRegistry=memory.docs.get(platformAuthorityRegistryDocumentPath());await assert.rejects(executeRevokePlatformAdmin(input(),deps),(e:unknown)=>e instanceof BackendError&&e.code===EC.FAILED_PRECONDITION);assert.equal(memory.docs.has(privilegedCommandDocumentPath("revoke-1")),false);assert.deepEqual(memory.docs.get(platformAuthorityDocumentPath("admin-b")),beforeAuthority);assert.deepEqual(memory.docs.get(platformAuthorityRegistryDocumentPath()),beforeRegistry);assert.equal(auth.writes.length,0);assert.equal([...memory.docs.keys()].filter(path=>path.startsWith("platformAuditEvents/")).length,0)}});
test("successful Revoke preserves unrelated claims, decrements once and replays",async()=>{const{memory,auth,deps}=setup();await executeRevokePlatformAdmin(input(),deps);assert.deepEqual(auth.users.get("admin-b")?.customClaims,{theme:"dark"});assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,1);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-b"))?.status,AS.REVOKED);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-b"))?.revokedBy,"admin-a");const writes=memory.writes.length,authWrites=auth.writes.length,replay=await executeRevokePlatformAdmin(input(),deps);assert.equal(replay.replayed,true);assert.equal(memory.writes.length,writes);assert.equal(auth.writes.length,authWrites)});
test("absent claim or missing Auth after prepare finalizes",async()=>{for(const missing of [false,true]){const{memory,auth,deps}=setup();if(missing)auth.missing=true;else auth.users.set("admin-b",{...auth.users.get("admin-b")!,customClaims:{theme:"dark"}});await executeRevokePlatformAdmin(input(missing?"revoke-missing":"revoke-absent"),deps);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-b"))?.status,AS.REVOKED);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,1)}});
test("unexpected and uncertain claims checkpoint and resume without second decrement",async()=>{for(const unexpected of [true,false]){const{memory,auth,deps}=setup();if(unexpected)auth.users.set("admin-b",{...auth.users.get("admin-b")!,customClaims:{platformRole:"student"}});else auth.fail=true;await assert.rejects(executeRevokePlatformAdmin(input(),deps),BackendError);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,1);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-b"))?.status,AS.RECOVERY_REQUIRED);if(!unexpected){auth.fail=false;await executeRevokePlatformAdmin(input(),deps);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,1);assert.equal(memory.docs.get(platformAuthorityDocumentPath("admin-b"))?.status,AS.REVOKED)}}});
test("foreign ownership and terminal lifecycle fail closed",async()=>{for(const target of [authority("admin-b",AS.PROVISIONING,"other"),authority("admin-b",AS.REVOKING,"other"),authority("admin-b",AS.REVOKED,null),authority("admin-b",AS.RECOVERY_REQUIRED,"other")]){const{memory,deps}=setup(2,target);await assert.rejects(executeRevokePlatformAdmin(input(),deps),BackendError);assert.equal(memory.docs.get(platformAuthorityRegistryDocumentPath())?.activeCount,2)}});
test("new invalid lifecycles leave no command, Authority, Registry, audit or Auth write",async()=>{for(const target of [authority("admin-b",AS.PROVISIONING,"revoke-1"),authority("admin-b",AS.REVOKING,"revoke-1"),authority("admin-b",AS.REVOKED,null),authority("admin-b",AS.RECOVERY_REQUIRED,"revoke-1")]){const{memory,auth,deps}=setup(2,target),beforeAuthority=memory.docs.get(platformAuthorityDocumentPath("admin-b")),beforeRegistry=memory.docs.get(platformAuthorityRegistryDocumentPath());await assert.rejects(executeRevokePlatformAdmin(input(),deps),BackendError);assert.equal(memory.docs.has(privilegedCommandDocumentPath("revoke-1")),false);assert.deepEqual(memory.docs.get(platformAuthorityDocumentPath("admin-b")),beforeAuthority);assert.deepEqual(memory.docs.get(platformAuthorityRegistryDocumentPath()),beforeRegistry);assert.equal(auth.writes.length,0);assert.equal([...memory.docs.keys()].filter(path=>path.startsWith("platformAuditEvents/")).length,0)}});
