import { randomUUID } from "node:crypto";
import { PLATFORM_AUTHORITY_REGISTRY_STATES, validatePlatformAuthority, validatePlatformAuthorityRegistry } from "@mipymetic/saas-contracts/authority";
import { CAPABILITY_IDS, MEMBERSHIP_ROLES, MEMBERSHIP_STATUSES, TENANT_STATUSES } from "@mipymetic/saas-contracts/domain";
import { COMMAND_STATUSES, COMMAND_TYPES, PRIVILEGED_COMMAND_STAGES, bootstrapTenantBehavioralPayload, validateBootstrapTenantInput, validateBootstrapTenantResult } from "@mipymetic/saas-contracts/commands";
import { BACKEND_ERROR_CODES } from "@mipymetic/saas-contracts/errors";
import { encodeMembershipUidKey, platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath, validateMembershipKey, validatePersistedTenant, validateTenantAdminAuthorityState, validateTenantBranding, validateTenantSettings } from "@mipymetic/saas-contracts/persistence";
import { validateDocumentIdentifier } from "@mipymetic/saas-contracts/validation";
import { requireAuthenticatedActor, type VerifiedAuthenticationContext } from "../authorization/authenticatedActor.js";
import { capabilitiesForPlatformRole, requireCapability } from "../authorization/capabilities.js";
import type { AuthorityResolution, JsonValue } from "../contracts/types.js";
import { BackendError, mapFirebaseAdminError } from "../errors/backendError.js";
import { canonicalPayloadHash } from "../idempotency/payloadHash.js";
import { serverOwnedTimestamp, type AuthoritativeReaderPort } from "../persistence/ports.js";
import type { TenantBootstrapTransactionStore } from "../persistence/tenantBootstrapTransactionStore.js";
import { validatePersistedCommandRecord } from "./commandRecord.js";
import type { BootstrapAuthPort, BootstrapIdentityPort } from "./bootstrapPlatformAdmins.js";

export interface BootstrapTenantInput {readonly commandId:string;readonly correlationId:string;readonly tenantId:string;readonly tenant:Readonly<Record<string,JsonValue>>;readonly settings:Readonly<Record<string,JsonValue>>;readonly branding:Readonly<Record<string,JsonValue>>;readonly firstAdminUid:string;readonly expectedAdminEmail:string;readonly initialStatus:"active"}
export interface BootstrapTenantResult {readonly commandId:string;readonly correlationId:string;readonly operation:"BootstrapTenant";readonly resourceType:"tenant";readonly resourceId:string;readonly status:"succeeded";readonly replayed:boolean}
export interface BootstrapTenantDependencies {readonly authContext:VerifiedAuthenticationContext|null;readonly reader:AuthoritativeReaderPort;readonly auth:Pick<BootstrapAuthPort,"getUser">;readonly identity:BootstrapIdentityPort;readonly store:TenantBootstrapTransactionStore;readonly generateMembershipId?:()=>string}
const invalid=():never=>{throw new BackendError(BACKEND_ERROR_CODES.INVALID_ARGUMENT,"BootstrapTenant input is invalid.")};
const result=(i:BootstrapTenantInput,replayed:boolean):BootstrapTenantResult=>Object.freeze({commandId:i.commandId,correlationId:i.correlationId,operation:"BootstrapTenant",resourceType:"tenant",resourceId:i.tenantId,status:"succeeded",replayed});

export const parseBootstrapTenantInput=(value:unknown):BootstrapTenantInput=>{const validation=validateBootstrapTenantInput(value);if(!validation.ok)return invalid();return validation.value as BootstrapTenantInput};
const eligibleAuth=async(d:BootstrapTenantDependencies,uid:string,email?:string)=>{try{const user=await d.auth.getUser(uid);if(user.uid!==uid||user.disabled||!user.emailVerified||user.email===null||(email!==undefined&&user.email.trim().toLowerCase()!==email))throw new BackendError(BACKEND_ERROR_CODES.FAILED_PRECONDITION,"Auth evidence is not eligible.");return user}catch(error){if(error instanceof BackendError)throw error;throw mapFirebaseAdminError(error)}};
const authority=async(d:BootstrapTenantDependencies,uid:string):Promise<AuthorityResolution>=>{const user=await eligibleAuth(d,uid);await d.identity.verify(uid,user.email!.trim().toLowerCase());const snapshot=await d.reader.read(platformAuthorityDocumentPath(uid),"platform_authority");if(!snapshot.exists)throw new BackendError(BACKEND_ERROR_CODES.FORBIDDEN,"Active Platform Authority is required.");const validation=validatePlatformAuthority(snapshot.data);if(!validation.ok)throw new BackendError(BACKEND_ERROR_CODES.CONTRACT_VIOLATION,"Platform Authority is malformed.");const value=validation.value;if(value.uid!==uid||value.status!=="active")throw new BackendError(BACKEND_ERROR_CODES.FORBIDDEN,"Active coherent Platform Authority is required.");const capabilities=capabilitiesForPlatformRole(value.authority);requireCapability(capabilities,CAPABILITY_IDS.PLATFORM_TENANT_CREATE);return Object.freeze({actorUid:uid,actorType:"platform_admin",authority:value.authority,tenantId:null,roles:Object.freeze([value.authority]),capabilities})};

export const executeBootstrapTenant=async(value:unknown,d:BootstrapTenantDependencies):Promise<BootstrapTenantResult>=>{
  const i=parseBootstrapTenantInput(value),actorUid=requireAuthenticatedActor(d.authContext).uid,operator=await authority(d,actorUid);
  const behavioral=bootstrapTenantBehavioralPayload(i as unknown as Readonly<Record<string,unknown>>) as Readonly<Record<string,JsonValue>>,payloadHash=canonicalPayloadHash(COMMAND_TYPES.BOOTSTRAP_TENANT,behavioral),commandSnapshot=await d.reader.read(privilegedCommandDocumentPath(i.commandId),"privileged_command");
  if(commandSnapshot.exists){const command=validatePersistedCommandRecord(commandSnapshot.data);if(command.commandType!==COMMAND_TYPES.BOOTSTRAP_TENANT||command.payloadHash!==payloadHash||command.correlationId!==i.correlationId)throw new BackendError(BACKEND_ERROR_CODES.CONFLICT,"BootstrapTenant command binding conflicts.");if(command.status!==COMMAND_STATUSES.SUCCEEDED||command.stage!==PRIVILEGED_COMMAND_STAGES.COMPLETED||!validateBootstrapTenantResult(command.result).ok)throw new BackendError(BACKEND_ERROR_CODES.CONTRACT_VIOLATION,"BootstrapTenant replay is malformed.");return result(i,true)}
  await d.identity.verify(i.firstAdminUid,i.expectedAdminEmail);await eligibleAuth(d,i.firstAdminUid,i.expectedAdminEmail);
  const registry=await d.reader.read(platformAuthorityRegistryDocumentPath(),"platform_authority_registry"),registryValidation=validatePlatformAuthorityRegistry(registry.data);if(!registry.exists||!registryValidation.ok)throw new BackendError(BACKEND_ERROR_CODES.CONTRACT_VIOLATION,"Platform Registry is missing or malformed.");if(registryValidation.value.bootstrapState!==PLATFORM_AUTHORITY_REGISTRY_STATES.COMPLETED)throw new BackendError(BACKEND_ERROR_CODES.FAILED_PRECONDITION,"Platform Registry is not completed.");
  const membershipId=(d.generateMembershipId??randomUUID)();if(!validateDocumentIdentifier(membershipId,"membershipId").ok)throw new BackendError(BACKEND_ERROR_CODES.CONTRACT_VIOLATION,"Generated Membership ID is invalid.");const uidKey=encodeMembershipUidKey(i.firstAdminUid),timestamp=serverOwnedTimestamp();
  const tenant={tenantId:i.tenantId,...i.tenant,status:TENANT_STATUSES.ACTIVE,createdAt:timestamp,updatedAt:timestamp,suspendedAt:null,archivedAt:null},settings={tenantId:i.tenantId,...i.settings,updatedAt:timestamp},branding={tenantId:i.tenantId,...i.branding,updatedAt:timestamp};
  const membership={membershipId,tenantId:i.tenantId,uid:i.firstAdminUid,role:MEMBERSHIP_ROLES.TENANT_ADMIN,status:MEMBERSHIP_STATUSES.APPROVED,originRequestId:null,createdAt:timestamp,approvedAt:timestamp,approvedBy:actorUid,updatedAt:timestamp,suspendedAt:null,removedAt:null};
  const membershipKey={tenantId:i.tenantId,uid:i.firstAdminUid,membershipId,status:MEMBERSHIP_STATUSES.APPROVED,originRequestId:null,updatedAt:timestamp},authorityState={tenantId:i.tenantId,activeCount:1,revision:1,lastCommandId:i.commandId,updatedAt:timestamp};
  const logical=registryValidation.value.updatedAt;if(!validatePersistedTenant({...tenant,createdAt:logical,updatedAt:logical}).ok||!validateTenantSettings({...settings,updatedAt:logical}).ok||!validateTenantBranding({...branding,updatedAt:logical}).ok||!validateMembershipKey({...membershipKey,updatedAt:logical}).ok||!validateTenantAdminAuthorityState({...authorityState,updatedAt:logical}).ok)throw new BackendError(BACKEND_ERROR_CODES.CONTRACT_VIOLATION,"BootstrapTenant aggregate violates shared contracts.");
  const stableResult=result(i,false);const outcome=await d.store.execute({commandId:i.commandId,correlationId:i.correlationId,payloadHash,tenantId:i.tenantId,membershipId,uidKey,actor:operator,tenant,settings,branding,membership,membershipKey,authorityState,result:stableResult as unknown as Readonly<Record<string,JsonValue>>});return result(i,outcome.replayed);
};
