import { PLATFORM_AUTHORITY_REGISTRY_STATES as RS, PLATFORM_AUTHORITY_STATUSES as AS, validatePlatformAuthority, validatePlatformAuthorityRegistry } from "@mipymetic/saas-contracts/authority";
import { COMMAND_STATUSES as CS, COMMAND_TYPES, PRIVILEGED_COMMAND_STAGES as ST } from "@mipymetic/saas-contracts/commands";
import { BACKEND_ERROR_CODES as EC } from "@mipymetic/saas-contracts/errors";
import { platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath } from "@mipymetic/saas-contracts/persistence";
import { validateDocumentIdentifier } from "@mipymetic/saas-contracts/validation";
import type { AuthorityResolution, CommandEnvelope, JsonValue } from "../contracts/types.js";
import type { BackendEnvironment } from "../config/config.js";
import { BackendError, mapFirebaseAdminError } from "../errors/backendError.js";
import { canonicalPayloadHash } from "../idempotency/payloadHash.js";
import type { AuthoritativeReaderPort, TransactionRunnerPort } from "../persistence/ports.js";
import type { PlatformCommandTransactionStore } from "../persistence/platformCommandTransactionStore.js";
import { runAuthoritativeTransaction } from "../persistence/transactionBoundary.js";
import { createPendingCommandRecord, validateCommandEnvelope, validatePersistedCommandRecord } from "./commandRecord.js";
import type { BootstrapAuthPort, BootstrapAuthUser, BootstrapIdentityPort } from "./bootstrapPlatformAdmins.js";

export interface RecoverPlatformAdminInput {readonly commandId:string;readonly correlationId:string;readonly environment:BackendEnvironment;readonly projectId:string;readonly confirmationId:string;readonly target:Readonly<{uid:string;expectedNormalizedEmail:string}>}
export interface RecoverApprovalPort {verify(input:Readonly<{confirmationId:string;environment:BackendEnvironment;projectId:string;targetUid:string;requiresTwoDistinctApprovers:true}>):Promise<boolean>}
export interface RecoverDependencies {readonly runner:TransactionRunnerPort;readonly reader:AuthoritativeReaderPort;readonly store:PlatformCommandTransactionStore;readonly approval:RecoverApprovalPort;readonly auth:BootstrapAuthPort;readonly identity:BootstrapIdentityPort;readonly operator:AuthorityResolution}
export interface RecoverPlatformAdminResult {readonly commandId:string;readonly correlationId:string;readonly operation:"RecoverPlatformAdmin";readonly resourceType:"platform_authority";readonly resourceId:string;readonly status:"succeeded";readonly replayed:boolean}

const fields=["commandId","correlationId","environment","projectId","confirmationId","target"], targetFields=["uid","expectedNormalizedEmail"], environments=new Set(["local","demo-emulator","development","staging","production"]);
const exact=(v:unknown,f:readonly string[])=>typeof v==="object"&&v!==null&&!Array.isArray(v)&&Object.keys(v).length===f.length&&Object.keys(v).every(k=>f.includes(k));
const email=(v:unknown):v is string=>typeof v==="string"&&v===v.trim().toLowerCase()&&/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v);
const invalid=(m:string):never=>{throw new BackendError(EC.INVALID_ARGUMENT,m)};
export const validateRecoverPlatformAdminInput=(value:unknown):RecoverPlatformAdminInput=>{if(!exact(value,fields))return invalid("Recover input has an invalid shape.");const v=value as Readonly<Record<string,unknown>>;if(!validateDocumentIdentifier(v.commandId,"commandId").ok||!validateDocumentIdentifier(v.correlationId,"correlationId").ok||!validateDocumentIdentifier(v.projectId,"projectId").ok||!validateDocumentIdentifier(v.confirmationId,"confirmationId").ok)return invalid("Recover identifiers are invalid.");if(typeof v.environment!=="string"||!environments.has(v.environment)||!exact(v.target,targetFields))return invalid("Recover scope is invalid.");const t=v.target as Readonly<Record<string,unknown>>;if(!validateDocumentIdentifier(t.uid,"target.uid").ok||!email(t.expectedNormalizedEmail))return invalid("Recover target is invalid.");return Object.freeze({commandId:v.commandId as string,correlationId:v.correlationId as string,environment:v.environment as BackendEnvironment,projectId:v.projectId as string,confirmationId:v.confirmationId as string,target:Object.freeze({uid:t.uid as string,expectedNormalizedEmail:t.expectedNormalizedEmail as string})})};
const outcome=(i:RecoverPlatformAdminInput,replayed:boolean):RecoverPlatformAdminResult=>Object.freeze({commandId:i.commandId,correlationId:i.correlationId,operation:"RecoverPlatformAdmin",resourceType:"platform_authority",resourceId:i.target.uid,status:"succeeded",replayed});
const authUser=async(d:RecoverDependencies,i:RecoverPlatformAdminInput):Promise<BootstrapAuthUser>=>{let u;try{u=await d.auth.getUser(i.target.uid)}catch(e){throw mapFirebaseAdminError(e)}if(u.uid!==i.target.uid||u.disabled||!u.emailVerified||u.email?.trim().toLowerCase()!==i.target.expectedNormalizedEmail)throw new BackendError(EC.FAILED_PRECONDITION,"Recover Auth user is not eligible.");return u};
const claimState=(u:BootstrapAuthUser)=>{const r=u.customClaims.platformRole;if(r===undefined)return "missing" as const;if(r==="platform_admin")return "correct" as const;throw new BackendError(EC.CONTRACT_VIOLATION,"Recover target has an unexpected platform role.")};
const audit=(d:RecoverDependencies,i:RecoverPlatformAdminInput,stage:string,result:"succeeded"|"recovery_required",code:string|null)=>({auditId:`${i.commandId}-${stage}`,authority:d.operator,operation:`RecoverPlatformAdmin.${stage}`,resourceType:"platform_authority",resourceId:i.target.uid,result,errorCode:code,beforeSummary:{},afterSummary:{},metadata:{stage,environment:i.environment,projectId:i.projectId,confirmationId:i.confirmationId}} as const);
const commandClaim=async(d:RecoverDependencies,i:RecoverPlatformAdminInput,envelope:CommandEnvelope,hash:string)=>runAuthoritativeTransaction(d.runner,async({transaction})=>{const path=privilegedCommandDocumentPath(i.commandId),s=await transaction.get(path,"privileged_command");if(!s.exists){transaction.create(path,createPendingCommandRecord({envelope,payloadHash:hash,authority:d.operator}));return {kind:"new" as const,record:null}}const r=validatePersistedCommandRecord(s.data);if(r.payloadHash!==hash||r.correlationId!==i.correlationId)throw new BackendError(EC.CONFLICT,"Command binding conflicts.");if(r.status===CS.SUCCEEDED&&r.stage===ST.COMPLETED)return {kind:"replay" as const,record:r};if((r.status===CS.RUNNING||r.status===CS.RECOVERY_REQUIRED)&&r.stage===ST.PREPARED)return {kind:"resume" as const,record:r};if(r.status===CS.PENDING&&r.stage===ST.NOT_STARTED)return {kind:"new" as const,record:r};throw new BackendError(EC.CONFLICT,"Recover command is incompatible.")});

export const executeRecoverPlatformAdmin=async(value:unknown,d:RecoverDependencies):Promise<RecoverPlatformAdminResult>=>{
 const i=validateRecoverPlatformAdminInput(value);if(!await d.approval.verify({confirmationId:i.confirmationId,environment:i.environment,projectId:i.projectId,targetUid:i.target.uid,requiresTwoDistinctApprovers:true}))throw new BackendError(EC.FORBIDDEN,"Recover approval is invalid.");await d.identity.verify(i.target.uid,i.target.expectedNormalizedEmail);let user=await authUser(d,i);
 const authoritySnap=await d.reader.read(platformAuthorityDocumentPath(i.target.uid),"platform_authority"),registrySnap=await d.reader.read(platformAuthorityRegistryDocumentPath(),"platform_authority_registry");if(!authoritySnap.exists)throw new BackendError(EC.NOT_FOUND,"Recover Authority is missing.");const av=validatePlatformAuthority(authoritySnap.data),rv=validatePlatformAuthorityRegistry(registrySnap.data);if(!av.ok||!rv.ok)throw new BackendError(EC.CONTRACT_VIOLATION,"Recover persistence is invalid.");const authority=av.value;if(authority.status===AS.REVOKED||authority.status===AS.REVOKING)throw new BackendError(EC.FAILED_PRECONDITION,"Authority cannot be recovered.");if(authority.status===AS.PROVISIONING&&authority.transitionCommandId!==i.commandId)throw new BackendError(EC.CONFLICT,"Authority has a foreign owner.");if(authority.status===AS.RECOVERY_REQUIRED&&authority.transitionCommandId===null)throw new BackendError(EC.CONTRACT_VIOLATION,"Recovery owner is missing.");
 const behavioral={environment:i.environment,projectId:i.projectId,confirmationId:i.confirmationId,target:i.target} as const,envelope:CommandEnvelope={commandId:i.commandId,commandType:COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,correlationId:i.correlationId,tenantId:null,payload:behavioral};validateCommandEnvelope(envelope);const hash=canonicalPayloadHash(envelope.commandType,envelope.payload),claimed=await commandClaim(d,i,envelope,hash);if(claimed.kind==="replay")return outcome(i,true);
 const activeOrigin=authority.status===AS.ACTIVE;if(claimed.kind==="new"){if(authority.status===AS.ACTIVE)await d.store.claimActiveRecoveryOwnership({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,targetUid:i.target.uid,audit:audit(d,i,"prepare","succeeded",null)});else if(authority.status===AS.RECOVERY_REQUIRED&&authority.transitionCommandId!==null&&authority.transitionCommandId!==i.commandId)await d.store.handoffRecoveryOwnership({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,targetUid:i.target.uid,priorCommandId:authority.transitionCommandId,audit:audit(d,i,"ownership_handoff","succeeded",null)});else throw new BackendError(EC.FAILED_PRECONDITION,"Recover target is not claimable.");}else if(authority.transitionCommandId!==i.commandId)throw new BackendError(EC.CONFLICT,"Recover resume owner conflicts.");
 try{user=await authUser(d,i);if(claimState(user)==="missing"){try{await d.auth.setCustomClaims(i.target.uid,Object.freeze({...user.customClaims,platformRole:"platform_admin"}))}catch(e){user=await authUser(d,i);if(claimState(user)!=="correct")throw mapFirebaseAdminError(e)}}await d.identity.verify(i.target.uid,i.target.expectedNormalizedEmail);user=await authUser(d,i);if(claimState(user)!=="correct")throw new BackendError(EC.CONTRACT_VIOLATION,"Recover claim verification failed.");}catch(e){const code=e instanceof BackendError?e.code:EC.UNKNOWN;await d.store.mutate({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,nextCommandStatus:CS.RECOVERY_REQUIRED,nextCommandStage:ST.PREPARED,commandResult:null,commandErrorCode:code,nextRegistryState:RS.RECOVERY_REQUIRED,activeCountDelta:0,authorities:[{uid:i.target.uid,expectedStatus:activeOrigin?AS.ACTIVE:AS.PROVISIONING,nextStatus:activeOrigin?AS.ACTIVE:AS.RECOVERY_REQUIRED,bootstrapCommandId:authority.bootstrapCommandId,retainTransitionOwner:activeOrigin}],audit:audit(d,i,"recovery_required","recovery_required",code)});throw e}
 const result=outcome(i,false);await d.store.mutate({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,nextCommandStatus:CS.SUCCEEDED,nextCommandStage:ST.COMPLETED,commandResult:result as unknown as JsonValue,commandErrorCode:null,nextRegistryState:RS.COMPLETED,activeCountDelta:activeOrigin?0:1,authorities:[{uid:i.target.uid,expectedStatus:activeOrigin?AS.ACTIVE:AS.PROVISIONING,nextStatus:AS.ACTIVE,bootstrapCommandId:authority.bootstrapCommandId,recordClaimSync:true}],audit:audit(d,i,"finalize","succeeded",null)});return result;
};
