import { CAPABILITY_IDS } from "@mipymetic/saas-contracts/domain";
import { PLATFORM_AUTHORITY_REGISTRY_STATES as RS,PLATFORM_AUTHORITY_STATUSES as AS,validatePlatformAuthority,validatePlatformAuthorityRegistry } from "@mipymetic/saas-contracts/authority";
import { COMMAND_STATUSES as CS,COMMAND_TYPES,PRIVILEGED_COMMAND_STAGES as ST } from "@mipymetic/saas-contracts/commands";
import { BACKEND_ERROR_CODES as EC } from "@mipymetic/saas-contracts/errors";
import { platformAuthorityDocumentPath,platformAuthorityRegistryDocumentPath,privilegedCommandDocumentPath } from "@mipymetic/saas-contracts/persistence";
import { validateDocumentIdentifier } from "@mipymetic/saas-contracts/validation";
import { requireAuthenticatedActor,type VerifiedAuthenticationContext } from "../authorization/authenticatedActor.js";
import { resolvePlatformAuthority } from "../authorization/authorityResolver.js";
import { requireCapability } from "../authorization/capabilities.js";
import type { AuthorityResolution,CommandEnvelope,JsonValue } from "../contracts/types.js";
import { BackendError,mapFirebaseAdminError } from "../errors/backendError.js";
import { canonicalPayloadHash } from "../idempotency/payloadHash.js";
import type { AuthoritativeReaderPort,TransactionRunnerPort } from "../persistence/ports.js";
import type { PlatformCommandTransactionStore } from "../persistence/platformCommandTransactionStore.js";
import { createPendingCommandRecord,validateCommandEnvelope,validatePersistedCommandRecord } from "./commandRecord.js";
import type { BootstrapAuthPort,BootstrapAuthUser,BootstrapIdentityPort } from "./bootstrapPlatformAdmins.js";

export interface RevokePlatformAdminInput{readonly commandId:string;readonly correlationId:string;readonly targetUid:string}
export interface RevokeDependencies{readonly authContext:VerifiedAuthenticationContext|null;readonly runner:TransactionRunnerPort;readonly reader:AuthoritativeReaderPort;readonly store:PlatformCommandTransactionStore;readonly auth:BootstrapAuthPort;readonly identity:BootstrapIdentityPort}
export interface RevokePlatformAdminResult{readonly commandId:string;readonly correlationId:string;readonly operation:"RevokePlatformAdmin";readonly resourceType:"platform_authority";readonly resourceId:string;readonly status:"succeeded";readonly replayed:boolean}
const fields=["commandId","correlationId","targetUid"];
const exact=(v:unknown)=>typeof v==="object"&&v!==null&&!Array.isArray(v)&&Object.keys(v).length===fields.length&&Object.keys(v).every(k=>fields.includes(k));
export const validateRevokePlatformAdminInput=(value:unknown):RevokePlatformAdminInput=>{if(!exact(value))throw new BackendError(EC.INVALID_ARGUMENT,"Revoke input has an invalid shape.");const v=value as Readonly<Record<string,unknown>>;if(!validateDocumentIdentifier(v.commandId,"commandId").ok||!validateDocumentIdentifier(v.correlationId,"correlationId").ok||!validateDocumentIdentifier(v.targetUid,"targetUid").ok)throw new BackendError(EC.INVALID_ARGUMENT,"Revoke identifiers are invalid.");return Object.freeze({commandId:v.commandId as string,correlationId:v.correlationId as string,targetUid:v.targetUid as string})};
const result=(i:RevokePlatformAdminInput,replayed:boolean):RevokePlatformAdminResult=>Object.freeze({commandId:i.commandId,correlationId:i.correlationId,operation:"RevokePlatformAdmin",resourceType:"platform_authority",resourceId:i.targetUid,status:"succeeded",replayed});
const audit=(authority:AuthorityResolution,i:RevokePlatformAdminInput,stage:string,outcome:"succeeded"|"recovery_required",code:string|null)=>({auditId:`${i.commandId}-${stage}`,authority,operation:`RevokePlatformAdmin.${stage}`,resourceType:"platform_authority",resourceId:i.targetUid,result:outcome,errorCode:code,beforeSummary:{},afterSummary:{},metadata:{stage}} as const);
const inspectCommand=async(d:RevokeDependencies,i:RevokePlatformAdminInput,hash:string)=>{const s=await d.reader.read(privilegedCommandDocumentPath(i.commandId),"privileged_command");if(!s.exists)return "new" as const;const r=validatePersistedCommandRecord(s.data);if(r.commandType!==COMMAND_TYPES.REVOKE_PLATFORM_ADMIN||r.payloadHash!==hash||r.correlationId!==i.correlationId)throw new BackendError(EC.CONFLICT,"Command binding conflicts.");if(r.status===CS.SUCCEEDED&&r.stage===ST.COMPLETED)return "replay" as const;if((r.status===CS.RUNNING||r.status===CS.RECOVERY_REQUIRED)&&r.stage===ST.PREPARED)return "resume" as const;throw new BackendError(EC.CONFLICT,"Revoke command is incompatible.")};
const readAuth=async(d:RevokeDependencies,uid:string):Promise<BootstrapAuthUser|null>=>{try{return await d.auth.getUser(uid)}catch(e){const mapped=mapFirebaseAdminError(e);if(mapped.code===EC.NOT_FOUND)return null;throw mapped}};

export const executeRevokePlatformAdmin=async(value:unknown,d:RevokeDependencies):Promise<RevokePlatformAdminResult>=>{const i=validateRevokePlatformAdminInput(value),actor=requireAuthenticatedActor(d.authContext);if(actor.uid===i.targetUid)throw new BackendError(EC.FORBIDDEN,"Self-revoke is forbidden.");const actorUser=await readAuth(d,actor.uid);if(actorUser===null||actorUser.disabled||!actorUser.emailVerified||actorUser.email===null)throw new BackendError(EC.FORBIDDEN,"Revoke actor is not eligible.");await d.identity.verify(actor.uid,actorUser.email.trim().toLowerCase());const authority=await resolvePlatformAuthority(d.reader,actor);requireCapability(authority.capabilities,CAPABILITY_IDS.PLATFORM_AUTHORITY_REVOKE);
 const targetSnap=await d.reader.read(platformAuthorityDocumentPath(i.targetUid),"platform_authority"),registrySnap=await d.reader.read(platformAuthorityRegistryDocumentPath(),"platform_authority_registry");if(!targetSnap.exists)throw new BackendError(EC.NOT_FOUND,"Revoke target is missing.");const av=validatePlatformAuthority(targetSnap.data),rv=validatePlatformAuthorityRegistry(registrySnap.data);if(!av.ok||!rv.ok)throw new BackendError(EC.CONTRACT_VIOLATION,"Revoke persistence is invalid.");const target=av.value;if(target.status===AS.PROVISIONING)throw new BackendError(EC.FAILED_PRECONDITION,"Revoke target lifecycle is invalid.");if(target.status===AS.ACTIVE&&target.transitionCommandId!==null)throw new BackendError(EC.CONFLICT,"Revoke target is owned.");if((target.status===AS.REVOKING||target.status===AS.RECOVERY_REQUIRED)&&target.transitionCommandId!==i.commandId)throw new BackendError(EC.CONFLICT,"Revoke target has a foreign owner.");
 const envelope:CommandEnvelope={commandId:i.commandId,commandType:COMMAND_TYPES.REVOKE_PLATFORM_ADMIN,correlationId:i.correlationId,tenantId:null,payload:{targetUid:i.targetUid}},hash=canonicalPayloadHash(envelope.commandType,envelope.payload);validateCommandEnvelope(envelope);const decision=await inspectCommand(d,i,hash);if(decision==="replay")return result(i,true);if(target.status===AS.REVOKED)throw new BackendError(EC.FAILED_PRECONDITION,"Revoke target is already revoked.");if(decision==="new"){await d.store.prepareRevokePlatformAdmin({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,targetUid:i.targetUid,command:createPendingCommandRecord({envelope,payloadHash:hash,authority}),audit:audit(authority,i,"prepare","succeeded",null)});}else if(target.status===AS.RECOVERY_REQUIRED)await d.store.resumeRevokeOwnership({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,targetUid:i.targetUid,audit:audit(authority,i,"resume","succeeded",null)});
 try{let user=await readAuth(d,i.targetUid);if(user!==null){const role=user.customClaims.platformRole;if(role!==undefined&&role!=="platform_admin")throw new BackendError(EC.CONTRACT_VIOLATION,"Revoke target has an unexpected platform role.");if(role==="platform_admin"){const claims={...user.customClaims};delete claims.platformRole;try{await d.auth.setCustomClaims(i.targetUid,Object.freeze(claims))}catch(e){user=await readAuth(d,i.targetUid);if(user!==null&&user.customClaims.platformRole!==undefined)throw mapFirebaseAdminError(e)}}user=await readAuth(d,i.targetUid);if(user!==null&&user.customClaims.platformRole!==undefined)throw new BackendError(EC.UNAVAILABLE,"Revoke claim verification failed.");}}catch(e){const code=e instanceof BackendError?e.code:EC.UNKNOWN;await d.store.markRevokeRecoveryRequired({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,targetUid:i.targetUid,audit:audit(authority,i,"recovery_required","recovery_required",code)});throw e}
 const out=result(i,false);await d.store.mutate({commandId:i.commandId,correlationId:i.correlationId,payloadHash:hash,nextCommandStatus:CS.SUCCEEDED,nextCommandStage:ST.COMPLETED,commandResult:out as unknown as JsonValue,commandErrorCode:null,nextRegistryState:RS.COMPLETED,activeCountDelta:0,authorities:[{uid:i.targetUid,expectedStatus:AS.REVOKING,nextStatus:AS.REVOKED,bootstrapCommandId:target.bootstrapCommandId}],audit:audit(authority,i,"finalize","succeeded",null)});return out};
