import assert from "node:assert/strict";
import test,{after,afterEach,before,beforeEach} from "node:test";
import {initializeApp,deleteApp} from "firebase-admin/app";
import {getFirestore,Timestamp} from "firebase-admin/firestore";
import {COMMAND_SCHEMA_VERSION,COMMAND_STATUSES as CS,COMMAND_TYPES,PRIVILEGED_COMMAND_STAGES as ST} from "@mipymetic/saas-contracts/commands";
import {PLATFORM_AUTHORITY_REGISTRY_STATES as RS,PLATFORM_AUTHORITY_STATUSES as AS} from "@mipymetic/saas-contracts/authority";
import {platformAuthorityDocumentPath,platformAuthorityRegistryDocumentPath,privilegedCommandDocumentPath} from "@mipymetic/saas-contracts/persistence";
import {executeBootstrapPlatformAdmins} from "../lib/commands/bootstrapPlatformAdmins.js";
import {createPlatformCommandTransactionStore} from "../lib/persistence/platformCommandTransactionStore.js";
import {FirestoreAdminTransactionRunner} from "../lib/persistence/adapters/firestore.js";

const projectId="demo-polish-learning-r4",app=initializeApp({projectId},"r4-bootstrap"),db=getFirestore(app),instant=Timestamp.fromDate(new Date("2026-01-01T00:00:00.000Z"));
const operator=Object.freeze({actorUid:"bootstrap-job",actorType:"system",authority:"platform_system",tenantId:null,roles:Object.freeze([]),capabilities:Object.freeze([])});
const payload=id=>({commandId:id,correlationId:`correlation-${id}`,environment:"local",confirmationId:"confirmation-1",targets:[{uid:"admin-a",expectedNormalizedEmail:"a@example.com"},{uid:"admin-b",expectedNormalizedEmail:"b@example.com"}]});
const registry=(state=RS.UNINITIALIZED,count=0,revision=0,last=null)=>({schemaVersion:1,bootstrapState:state,activeCount:count,revision,lastCommandId:last,updatedAt:instant});
const command=(id,status=CS.RUNNING,stage=ST.PREPARED)=>({commandId:id,commandType:COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,payloadHash:"placeholder",actorUid:"bootstrap-job",actorType:"system",authority:"platform_system",tenantId:null,status,stage,startedAt:instant,completedAt:null,failedAt:null,result:null,errorCode:null,attemptCount:0,correlationId:`correlation-${id}`,expiresAt:null,leaseExpiresAt:null,schemaVersion:COMMAND_SCHEMA_VERSION});
const authority=(uid,id,status=AS.PROVISIONING)=>({schemaVersion:1,transitionCommandId:id,uid,authority:"platform_admin",status,createdAt:instant,createdBy:id,updatedAt:instant,updatedBy:id,activatedAt:null,revokedAt:null,revokedBy:null,bootstrapCommandId:id,lastClaimSyncAt:null});
class Auth{constructor(correct=false){this.users=new Map([["admin-a",{uid:"admin-a",email:"a@example.com",emailVerified:true,disabled:false,customClaims:correct?{platformRole:"platform_admin"}:{} }],["admin-b",{uid:"admin-b",email:"b@example.com",emailVerified:true,disabled:false,customClaims:correct?{platformRole:"platform_admin"}:{} }]])}failB=false;async getUser(uid){return Object.freeze({...this.users.get(uid),customClaims:Object.freeze({...this.users.get(uid).customClaims})})}async setCustomClaims(uid,claims){if(this.failB&&uid==="admin-b")throw Object.assign(new Error("uncertain"),{code:"auth/internal-error"});this.users.set(uid,{...this.users.get(uid),customClaims:{...claims}})}}
const dependencies=auth=>{const runner=new FirestoreAdminTransactionRunner(db);return{runner,store:createPlatformCommandTransactionStore(runner),approval:{verify:async()=>true},auth,identity:{verify:async()=>undefined},operator}};
const clear=async()=>{for(const collection of ["platformAuditEvents","platformAuthorities","privilegedCommands","platformControl"]){const snapshot=await db.collection(collection).get();if(!snapshot.empty){const batch=db.batch();snapshot.docs.forEach(doc=>batch.delete(doc.ref));await batch.commit()}}};
const seed=async docs=>{const batch=db.batch();for(const [path,data]of docs)batch.set(db.doc(path),data);await batch.commit()};
const hashFor=async id=>{const {canonicalPayloadHash}=await import("../lib/idempotency/payloadHash.js");return canonicalPayloadHash(COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,{environment:"local",confirmationId:"confirmation-1",targets:payload(id).targets})};
let emulatorCaseRunning=false;const emulatorCaseQueue=[];beforeEach(()=>new Promise(resolve=>{if(!emulatorCaseRunning){emulatorCaseRunning=true;resolve()}else emulatorCaseQueue.push(resolve)}));afterEach(()=>{const next=emulatorCaseQueue.shift();if(next)next();else emulatorCaseRunning=false});
before(clear);after(async()=>{await clear();await db.terminate();await deleteApp(app)});

test("competing Bootstrap commands produce one recovery owner without duplicate prepare",async()=>{await clear();await seed([[platformAuthorityRegistryDocumentPath(),registry()]]);const auth=new Auth();auth.failB=true;const results=await Promise.allSettled([executeBootstrapPlatformAdmins(payload("boot-a"),dependencies(auth)),executeBootstrapPlatformAdmins(payload("boot-b"),dependencies(auth))]);assert.equal(results.filter(r=>r.status==="fulfilled").length,0,results.map(r=>r.status==="rejected"?String(r.reason?.stack??r.reason):"fulfilled").join("\n"));const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data(),rawCommands=await db.collection("privilegedCommands").get(),timestampTypes=rawCommands.docs.map(doc=>`${doc.id}:${doc.data().startedAt?.constructor?.name}:${typeof doc.data().startedAt?.toDate}`);assert.equal(reg.bootstrapState,RS.RECOVERY_REQUIRED,`${results.map(r=>r.status==="rejected"?String(r.reason?.stack??r.reason):"fulfilled").join("\n")}\n${timestampTypes.join(",")}`);assert.equal(reg.activeCount,0);assert.equal(reg.revision,2);assert.ok(["boot-a","boot-b"].includes(reg.lastCommandId));assert.equal((await db.collection("platformAuthorities").get()).size,2);assert.equal((await db.collection("platformAuditEvents").where("operation","==","BootstrapPlatformAdmins.prepare").get()).size,1)});

test("concurrent finalize is idempotent and never produces activeCount four",async()=>{await clear();const id="finalize-1",cmd={...command(id),payloadHash:await hashFor(id)};await seed([[platformAuthorityRegistryDocumentPath(),registry(RS.IN_PROGRESS,0,1,id)],[privilegedCommandDocumentPath(id),cmd],[platformAuthorityDocumentPath("admin-a"),authority("admin-a",id)],[platformAuthorityDocumentPath("admin-b"),authority("admin-b",id)]]);const auth=new Auth(true),deps=dependencies(auth);const results=await Promise.allSettled([executeBootstrapPlatformAdmins(payload(id),deps),executeBootstrapPlatformAdmins(payload(id),deps)]);assert.equal(results.filter(r=>r.status==="fulfilled").length,2,results.map(r=>r.status==="rejected"?String(r.reason?.stack??r.reason):"fulfilled").join("\n"));const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(reg.activeCount,2);assert.equal(reg.revision,2);assert.equal((await db.collection("platformAuditEvents").where("operation","==","BootstrapPlatformAdmins.finalize").get()).size,1)});

test("recovery_required resumes same owner and finalizes without duplicate prepare",async()=>{await clear();const id="recover-1",cmd={...command(id,CS.RECOVERY_REQUIRED),payloadHash:await hashFor(id),errorCode:"UNKNOWN"};await seed([[platformAuthorityRegistryDocumentPath(),registry(RS.RECOVERY_REQUIRED,0,2,id)],[privilegedCommandDocumentPath(id),cmd],[platformAuthorityDocumentPath("admin-a"),authority("admin-a",id,AS.RECOVERY_REQUIRED)],[platformAuthorityDocumentPath("admin-b"),authority("admin-b",id,AS.RECOVERY_REQUIRED)]]);const auth=new Auth();auth.users.get("admin-a").customClaims={platformRole:"platform_admin"};const completed=await executeBootstrapPlatformAdmins(payload(id),dependencies(auth));assert.equal(completed.status,"succeeded");const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(reg.activeCount,2);assert.equal(reg.bootstrapState,RS.COMPLETED);assert.equal((await db.collection("platformAuditEvents").where("operation","==","BootstrapPlatformAdmins.prepare").get()).size,0)});
