import assert from "node:assert/strict";
import test, { after, before } from "node:test";
import { initializeApp, deleteApp } from "firebase-admin/app";
import { getFirestore, Timestamp } from "firebase-admin/firestore";
import { COMMAND_SCHEMA_VERSION, COMMAND_STATUSES as CS, COMMAND_TYPES, PRIVILEGED_COMMAND_STAGES as ST } from "@mipymetic/saas-contracts/commands";
import { PLATFORM_AUTHORITY_SCHEMA_VERSION, PLATFORM_AUTHORITY_REGISTRY_STATES as RS, PLATFORM_AUTHORITY_STATUSES as AS } from "@mipymetic/saas-contracts/authority";
import { platformAuthorityDocumentPath, platformAuthorityRegistryDocumentPath, privilegedCommandDocumentPath } from "@mipymetic/saas-contracts/persistence";
import { FirestoreAdminTransactionRunner } from "../lib/persistence/adapters/firestore.js";
import { createPlatformCommandTransactionStore } from "../lib/persistence/platformCommandTransactionStore.js";

const projectId="demo-polish-learning-r3-r7", app=initializeApp({projectId},"r3-r7-emulator"), db=getFirestore(app), instant=Timestamp.fromDate(new Date("2026-01-01T00:00:00.000Z"));
const actor=Object.freeze({actorUid:"actor-1",actorType:"platform_admin",authority:"platform_admin",tenantId:null,roles:Object.freeze(["platform_admin"]),capabilities:Object.freeze([])});
const command=(id,type)=>({commandId:id,commandType:type,payloadHash:"a".repeat(64),actorUid:"actor-1",actorType:"platform_admin",authority:"platform_admin",tenantId:null,status:CS.PENDING,stage:ST.NOT_STARTED,startedAt:instant,completedAt:null,failedAt:null,result:null,errorCode:null,attemptCount:0,correlationId:`correlation-${id}`,expiresAt:null,leaseExpiresAt:null,schemaVersion:COMMAND_SCHEMA_VERSION});
const registry=(count,state=RS.UNINITIALIZED,revision=0,last=null)=>({schemaVersion:1,bootstrapState:state,activeCount:count,revision,lastCommandId:last,updatedAt:instant});
const authority=(uid)=>({schemaVersion:PLATFORM_AUTHORITY_SCHEMA_VERSION,transitionCommandId:null,uid,authority:"platform_admin",status:AS.ACTIVE,createdAt:instant,createdBy:"seed-command",updatedAt:instant,updatedBy:"seed-command",activatedAt:instant,revokedAt:null,revokedBy:null,bootstrapCommandId:null,lastClaimSyncAt:null});
const input=(id,type,uid,auditId)=>({commandId:id,correlationId:`correlation-${id}`,payloadHash:"a".repeat(64),nextCommandStatus:CS.RUNNING,nextCommandStage:ST.PREPARED,commandResult:null,commandErrorCode:null,nextRegistryState:type===COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS?RS.IN_PROGRESS:RS.COMPLETED,activeCountDelta:type===COMMAND_TYPES.REVOKE_PLATFORM_ADMIN?-1:0,authorities:type===COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS?[{uid:"boot-a",expectedStatus:null,nextStatus:AS.PROVISIONING,bootstrapCommandId:id},{uid:"boot-b",expectedStatus:null,nextStatus:AS.PROVISIONING,bootstrapCommandId:id}]:[{uid,expectedStatus:AS.ACTIVE,nextStatus:AS.REVOKING,bootstrapCommandId:null}],audit:{auditId,authority:actor,operation:`${type}.prepare`,resourceType:"platform_authority_registry",resourceId:"authorityRegistry",result:"succeeded",errorCode:null,beforeSummary:{},afterSummary:{},metadata:{stage:"prepare"}}});
const seed=async(documents)=>{const batch=db.batch();for(const [path,data] of documents)batch.set(db.doc(path),data);await batch.commit()};
const clear=async()=>{for(const collection of ["platformAuditEvents","platformAuthorities","privilegedCommands","platformControl"]){const snapshot=await db.collection(collection).get();if(!snapshot.empty){const batch=db.batch();snapshot.docs.forEach(doc=>batch.delete(doc.ref));await batch.commit()}}};
before(clear);after(async()=>{await clear();await db.terminate();await deleteApp(app)});

test("competing bootstrap commands produce exactly one transactional owner",async()=>{await clear();await seed([[platformAuthorityRegistryDocumentPath(),registry(0)],[privilegedCommandDocumentPath("boot-1"),command("boot-1",COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS)],[privilegedCommandDocumentPath("boot-2"),command("boot-2",COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS)]]);const store=createPlatformCommandTransactionStore(new FirestoreAdminTransactionRunner(db));const first=store.mutate(input("boot-1",COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,"","audit-boot-1"));await new Promise(resolve=>setTimeout(resolve,750));const results=await Promise.allSettled([first,store.mutate(input("boot-2",COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,"","audit-boot-2"))]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(results.filter(r=>r.status==="rejected").length,1);const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(reg.activeCount,0);assert.equal(reg.revision,1);assert.ok(["boot-1","boot-2"].includes(reg.lastCommandId));assert.equal((await db.collection("platformAuditEvents").get()).size,1)});

test("different commands competing for one Authority produce one owner",async()=>{await clear();await seed([[platformAuthorityRegistryDocumentPath(),registry(2,RS.COMPLETED,5,"seed-command")],[platformAuthorityDocumentPath("admin-a"),authority("admin-a")],[privilegedCommandDocumentPath("revoke-1"),command("revoke-1",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN)],[privilegedCommandDocumentPath("revoke-2"),command("revoke-2",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN)]]);const store=createPlatformCommandTransactionStore(new FirestoreAdminTransactionRunner(db));const results=await Promise.allSettled([store.mutate(input("revoke-1",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN,"admin-a","audit-r1")),store.mutate(input("revoke-2",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN,"admin-a","audit-r2"))]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(results.filter(r=>r.status==="rejected").length,1);const persisted=(await db.doc(platformAuthorityDocumentPath("admin-a")).get()).data();assert.equal(persisted.status,AS.REVOKING);assert.ok(["revoke-1","revoke-2"].includes(persisted.transitionCommandId));assert.equal((await db.doc(platformAuthorityRegistryDocumentPath()).get()).data().activeCount,1)});

test("same-owner prepared resume is a safe no-count mutation",async()=>{await clear();const prepared={...command("recover-1",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN),status:CS.RECOVERY_REQUIRED,stage:ST.PREPARED};const owned={...authority("admin-a"),status:AS.RECOVERY_REQUIRED,transitionCommandId:"recover-1",activatedAt:null};await seed([[platformAuthorityRegistryDocumentPath(),registry(1,RS.RECOVERY_REQUIRED,4,"recover-1")],[platformAuthorityDocumentPath("admin-a"),owned],[privilegedCommandDocumentPath("recover-1"),prepared]]);const store=createPlatformCommandTransactionStore(new FirestoreAdminTransactionRunner(db));const request={...input("recover-1",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"admin-a","audit-resume"),activeCountDelta:0,nextRegistryState:RS.IN_PROGRESS,authorities:[{uid:"admin-a",expectedStatus:AS.RECOVERY_REQUIRED,nextStatus:AS.PROVISIONING,bootstrapCommandId:null}]};await store.mutate(request);const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(reg.activeCount,1);assert.equal(reg.revision,5);assert.equal((await db.doc(platformAuthorityDocumentPath("admin-a")).get()).data().transitionCommandId,"recover-1")});

test("two concurrent revokes retry and leave exactly one active",async()=>{await clear();await seed([[platformAuthorityRegistryDocumentPath(),registry(2,RS.COMPLETED,8,"seed-command")],[platformAuthorityDocumentPath("admin-a"),authority("admin-a")],[platformAuthorityDocumentPath("admin-b"),authority("admin-b")],[privilegedCommandDocumentPath("revoke-a"),command("revoke-a",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN)],[privilegedCommandDocumentPath("revoke-b"),command("revoke-b",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN)]]);let callbacks=0;const runner=new FirestoreAdminTransactionRunner(db);const store=createPlatformCommandTransactionStore({run:(operation)=>runner.run(tx=>{callbacks+=1;return operation(tx)})});const results=await Promise.allSettled([store.mutate(input("revoke-a",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN,"admin-a","audit-a")),store.mutate(input("revoke-b",COMMAND_TYPES.REVOKE_PLATFORM_ADMIN,"admin-b","audit-b"))]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(results.filter(r=>r.status==="rejected").length,1);const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(reg.activeCount,1);assert.equal(reg.revision,9);assert.ok(callbacks>=3);assert.equal((await db.collection("platformAuditEvents").get()).size,1)});

test("server timestamp writes persist native Timestamp and normalize on Store reread",async()=>{const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.ok(reg.updatedAt instanceof Timestamp);const audit=(await db.collection("platformAuditEvents").limit(1).get()).docs[0]?.data();assert.ok(audit.requestedAt instanceof Timestamp);assert.ok(audit.executedAt instanceof Timestamp)});

const ownershipRequest=(id,operation="RecoverPlatformAdmin.prepare")=>({commandId:id,correlationId:`correlation-${id}`,payloadHash:"a".repeat(64),targetUid:"admin-a",audit:{auditId:`audit-${id}`,authority:actor,operation,resourceType:"platform_authority",resourceId:"admin-a",result:"succeeded",errorCode:null,beforeSummary:{},afterSummary:{},metadata:{stage:"prepare"}}});
test("two Recover commands claiming one active Authority produce exactly one owner",async()=>{await clear();await seed([[platformAuthorityRegistryDocumentPath(),registry(2,RS.COMPLETED,10,"seed-command")],[platformAuthorityDocumentPath("admin-a"),authority("admin-a")],[privilegedCommandDocumentPath("recover-a"),command("recover-a",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN)],[privilegedCommandDocumentPath("recover-b"),command("recover-b",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN)]]);let callbacks=0;const base=new FirestoreAdminTransactionRunner(db),store=createPlatformCommandTransactionStore({run:operation=>base.run(tx=>{callbacks+=1;return operation(tx)})});const results=await Promise.allSettled([store.claimActiveRecoveryOwnership(ownershipRequest("recover-a")),store.claimActiveRecoveryOwnership(ownershipRequest("recover-b"))]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);assert.equal(results.filter(result=>result.status==="rejected").length,1);const persisted=(await db.doc(platformAuthorityDocumentPath("admin-a")).get()).data(),reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(persisted.status,AS.ACTIVE);assert.ok(["recover-a","recover-b"].includes(persisted.transitionCommandId));assert.equal(reg.activeCount,2);assert.equal(reg.revision,11);assert.equal((await db.collection("platformAuditEvents").get()).size,1);assert.ok(callbacks>=2)});
test("competing eligible handoffs produce one new Recover owner",async()=>{await clear();const prior={...command("recover-old",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN),status:CS.RECOVERY_REQUIRED,stage:ST.PREPARED},owned={...authority("admin-a"),status:AS.RECOVERY_REQUIRED,transitionCommandId:"recover-old",activatedAt:null};await seed([[platformAuthorityRegistryDocumentPath(),registry(1,RS.RECOVERY_REQUIRED,12,"recover-old")],[platformAuthorityDocumentPath("admin-a"),owned],[privilegedCommandDocumentPath("recover-old"),prior],[privilegedCommandDocumentPath("recover-b"),command("recover-b",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN)],[privilegedCommandDocumentPath("recover-c"),command("recover-c",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN)]]);const store=createPlatformCommandTransactionStore(new FirestoreAdminTransactionRunner(db));const results=await Promise.allSettled([store.handoffRecoveryOwnership({...ownershipRequest("recover-b","RecoverPlatformAdmin.ownership_handoff"),priorCommandId:"recover-old"}),store.handoffRecoveryOwnership({...ownershipRequest("recover-c","RecoverPlatformAdmin.ownership_handoff"),priorCommandId:"recover-old"})]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);assert.equal(results.filter(result=>result.status==="rejected").length,1);const persisted=(await db.doc(platformAuthorityDocumentPath("admin-a")).get()).data(),reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(persisted.status,AS.PROVISIONING);assert.ok(["recover-b","recover-c"].includes(persisted.transitionCommandId));assert.equal(reg.activeCount,1);assert.equal(reg.revision,13);assert.equal((await db.collection("platformAuditEvents").get()).size,1)});
test("Bootstrap and Revoke owners cannot use the Recover handoff",async()=>{for(const type of [COMMAND_TYPES.BOOTSTRAP_PLATFORM_ADMINS,COMMAND_TYPES.REVOKE_PLATFORM_ADMIN]){await clear();const prior={...command("prior-owner",type),status:CS.RECOVERY_REQUIRED,stage:ST.PREPARED},owned={...authority("admin-a"),status:AS.RECOVERY_REQUIRED,transitionCommandId:"prior-owner",activatedAt:null};await seed([[platformAuthorityRegistryDocumentPath(),registry(1,RS.RECOVERY_REQUIRED,20,"prior-owner")],[platformAuthorityDocumentPath("admin-a"),owned],[privilegedCommandDocumentPath("prior-owner"),prior],[privilegedCommandDocumentPath("recover-new"),command("recover-new",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN)]]);const store=createPlatformCommandTransactionStore(new FirestoreAdminTransactionRunner(db));await assert.rejects(store.handoffRecoveryOwnership({...ownershipRequest("recover-new","RecoverPlatformAdmin.ownership_handoff"),priorCommandId:"prior-owner"}));const persisted=(await db.doc(platformAuthorityDocumentPath("admin-a")).get()).data(),reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data();assert.equal(persisted.transitionCommandId,"prior-owner");assert.equal(reg.revision,20);assert.equal((await db.collection("platformAuditEvents").get()).size,0)}});
test("concurrent Recovery finalization increments activeCount exactly once",async()=>{await clear();const prepared={...command("recover-final",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN),status:CS.RUNNING,stage:ST.PREPARED},owned={...authority("admin-a"),status:AS.PROVISIONING,transitionCommandId:"recover-final",activatedAt:null};await seed([[platformAuthorityRegistryDocumentPath(),registry(1,RS.IN_PROGRESS,30,"recover-final")],[platformAuthorityDocumentPath("admin-a"),owned],[privilegedCommandDocumentPath("recover-final"),prepared]]);const store=createPlatformCommandTransactionStore(new FirestoreAdminTransactionRunner(db)),finalize={...input("recover-final",COMMAND_TYPES.RECOVER_PLATFORM_ADMIN,"admin-a","audit-recover-final"),nextCommandStatus:CS.SUCCEEDED,nextCommandStage:ST.COMPLETED,nextRegistryState:RS.COMPLETED,activeCountDelta:1,authorities:[{uid:"admin-a",expectedStatus:AS.PROVISIONING,nextStatus:AS.ACTIVE,bootstrapCommandId:null,recordClaimSync:true}]};const results=await Promise.allSettled([store.mutate(finalize),store.mutate(finalize)]);assert.equal(results.filter(result=>result.status==="fulfilled").length,2);const reg=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data(),persisted=(await db.doc(platformAuthorityDocumentPath("admin-a")).get()).data();assert.equal(reg.activeCount,2);assert.equal(reg.revision,31);assert.equal(persisted.status,AS.ACTIVE);assert.equal(persisted.transitionCommandId,null);assert.equal((await db.collection("platformAuditEvents").get()).size,1)});
