import assert from "node:assert/strict";import test,{after,before}from"node:test";import{initializeApp,deleteApp}from"firebase-admin/app";import{getFirestore,Timestamp}from"firebase-admin/firestore";
import{PLATFORM_AUTHORITY_SCHEMA_VERSION,PLATFORM_AUTHORITY_REGISTRY_STATES as RS,PLATFORM_AUTHORITY_STATUSES as AS}from"@mipymetic/saas-contracts/authority";import{identityDocumentPath,platformAuthorityDocumentPath,platformAuthorityRegistryDocumentPath}from"@mipymetic/saas-contracts/persistence";
import{executeRevokePlatformAdmin}from"../lib/commands/revokePlatformAdmin.js";import{createFirestoreBootstrapIdentityPort}from"../lib/commands/bootstrapPlatformAdmins.js";import{createPlatformCommandTransactionStore}from"../lib/persistence/platformCommandTransactionStore.js";import{FirestoreAdminReader,FirestoreAdminTransactionRunner}from"../lib/persistence/adapters/firestore.js";
const app=initializeApp({projectId:"demo-polish-learning-r6"},"r6-revoke"),db=getFirestore(app),instant=Timestamp.fromDate(new Date("2026-01-01T00:00:00.000Z"));const registry=(n=2)=>({schemaVersion:1,bootstrapState:RS.COMPLETED,activeCount:n,revision:1,lastCommandId:"bootstrap",updatedAt:instant}),identity=u=>({uid:u,email:`${u}@example.com`,displayName:u,photoURL:null,emailVerified:true,interfaceLocale:"en",createdAt:instant,updatedAt:instant}),authority=u=>({schemaVersion:PLATFORM_AUTHORITY_SCHEMA_VERSION,transitionCommandId:null,uid:u,authority:"platform_admin",status:AS.ACTIVE,createdAt:instant,createdBy:"bootstrap",updatedAt:instant,updatedBy:"bootstrap",activatedAt:instant,revokedAt:null,revokedBy:null,bootstrapCommandId:"bootstrap",lastClaimSyncAt:null});
class Auth{constructor(){this.users=new Map(["admin-a","admin-b","admin-c"].map(u=>[u,{uid:u,email:`${u}@example.com`,emailVerified:true,disabled:false,customClaims:{theme:"dark",platformRole:"platform_admin"}}]));this.writes=[]}async getUser(u){const x=this.users.get(u);if(!x)throw Object.assign(new Error("missing"),{code:"auth/user-not-found"});return x}async setCustomClaims(u,c){this.writes.push(u);this.users.set(u,{...this.users.get(u),customClaims:{...c}})}}
const clear=async()=>{for(const c of["platformAuditEvents","platformAuthorities","privilegedCommands","platformControl","identities"]){const s=await db.collection(c).get();if(!s.empty){const b=db.batch();s.docs.forEach(d=>b.delete(d.ref));await b.commit()}}},seed=async(count=2)=>{const b=db.batch();b.set(db.doc(platformAuthorityRegistryDocumentPath()),registry(count));for(const u of["admin-a","admin-b","admin-c"]){b.set(db.doc(identityDocumentPath(u)),identity(u));b.set(db.doc(platformAuthorityDocumentPath(u)),authority(u))}await b.commit()},deps=a=>{const runner=new FirestoreAdminTransactionRunner(db),reader=new FirestoreAdminReader(db);return{authContext:{uid:"admin-a",token:{email_verified:true}},runner,reader,store:createPlatformCommandTransactionStore(runner),auth:a,identity:createFirestoreBootstrapIdentityPort(reader)}};before(clear);after(async()=>{await clear();await db.terminate();await deleteApp(app)});
test("successful revoke decrements once, preserves claims and replays",async()=>{await clear();await seed();const a=new Auth(),p={commandId:"revoke-b",correlationId:"correlation-b",targetUid:"admin-b"};await executeRevokePlatformAdmin(p,deps(a));await executeRevokePlatformAdmin(p,deps(a));const r=(await db.doc(platformAuthorityRegistryDocumentPath()).get()).data(),x=(await db.doc(platformAuthorityDocumentPath("admin-b")).get()).data();assert.equal(r.activeCount,1);assert.equal(x.status,AS.REVOKED);assert.deepEqual(a.users.get("admin-b").customClaims,{theme:"dark"});assert.equal((await db.collection("platformAuditEvents").get()).size,2)});
test("last-two concurrent revokes leave exactly one active",async()=>{await clear();await seed();const a=new Auth(),d=deps(a),results=await Promise.allSettled([executeRevokePlatformAdmin({commandId:"revoke-b",correlationId:"correlation-b",targetUid:"admin-b"},d),executeRevokePlatformAdmin({commandId:"revoke-c",correlationId:"correlation-c",targetUid:"admin-c"},d)]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal((await db.doc(platformAuthorityRegistryDocumentPath()).get()).data().activeCount,1);assert.equal((await db.collection("platformAuditEvents").get()).size,2)});
test("same-target contention selects one owner and no double decrement",async()=>{await clear();await seed(3);const a=new Auth(),d=deps(a),results=await Promise.allSettled([executeRevokePlatformAdmin({commandId:"revoke-1",correlationId:"correlation-1",targetUid:"admin-b"},d),executeRevokePlatformAdmin({commandId:"revoke-2",correlationId:"correlation-2",targetUid:"admin-b"},d)]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal((await db.doc(platformAuthorityRegistryDocumentPath()).get()).data().activeCount,2);assert.equal((await db.doc(platformAuthorityDocumentPath("admin-b")).get()).data().status,AS.REVOKED)});
