// src/utils/countries.js

export const countries = [
  { code: 'AF', name: 'Afganistan', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'DE', name: 'Niemcy', flag: '🇩🇪' },
  { code: 'AD', name: 'Andora', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮' },
  { code: 'AQ', name: 'Antarktyda', flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua i Barbuda', flag: '🇦🇬' },
  { code: 'SA', name: 'Arabia Saudyjska', flag: '🇸🇦' },
  { code: 'DZ', name: 'Algieria', flag: '🇩🇿' },
  { code: 'AR', name: 'Argentyna', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbejdżan', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamy', flag: '🇧🇸' },
  { code: 'BD', name: 'Bangladesz', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BH', name: 'Bahrajn', flag: '🇧🇭' },
  { code: 'BE', name: 'Belgia', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermudy', flag: '🇧🇲' },
  { code: 'BY', name: 'Białoruś', flag: '🇧🇾' },
  { code: 'BO', name: 'Boliwia', flag: '🇧🇴' },
  { code: 'BA', name: 'Bośnia i Hercegowina', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', name: 'Brazylia', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'Bułgaria', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹' },
  { code: 'CV', name: 'Republika Zielonego Przylądka', flag: '🇨🇻' },
  { code: 'KH', name: 'Kambodża', flag: '🇰🇭' },
  { code: 'CM', name: 'Kamerun', flag: '🇨🇲' },
  { code: 'CA', name: 'Kanada', flag: '🇨🇦' },
  { code: 'TD', name: 'Czad', flag: '🇹🇩' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CN', name: 'Chiny', flag: '🇨🇳' },
  { code: 'CY', name: 'Cypr', flag: '🇨🇾' },
  { code: 'CO', name: 'Kolumbia', flag: '🇨🇴' },
  { code: 'KM', name: 'Komory', flag: '🇰🇲' },
  { code: 'CG', name: 'Kongo', flag: '🇨🇬' },
  { code: 'KP', name: 'Korea Północna', flag: '🇰🇵' },
  { code: 'KR', name: 'Korea Południowa', flag: '🇰🇷' },
  { code: 'CI', name: 'Wybrzeże Kości Słoniowej', flag: '🇨🇮' },
  { code: 'CR', name: 'Kostaryka', flag: '🇨🇷' },
  { code: 'HR', name: 'Chorwacja', flag: '🇭🇷' },
  { code: 'CU', name: 'Kuba', flag: '🇨🇺' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼' },
  { code: 'DK', name: 'Dania', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominika', flag: '🇩🇲' },
  { code: 'EC', name: 'Ekwador', flag: '🇪🇨' },
  { code: 'EG', name: 'Egipt', flag: '🇪🇬' },
  { code: 'SV', name: 'Salwador', flag: '🇸🇻' },
  { code: 'AE', name: 'Zjednoczone Emiraty Arabskie', flag: '🇦🇪' },
  { code: 'ER', name: 'Erytrea', flag: '🇪🇷' },
  { code: 'SK', name: 'Słowacja', flag: '🇸🇰' },
  { code: 'SI', name: 'Słowenia', flag: '🇸🇮' },
  { code: 'ES', name: 'Hiszpania', flag: '🇪🇸' },
  { code: 'US', name: 'Stany Zjednoczone', flag: '🇺🇸' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'ET', name: 'Etiopia', flag: '🇪🇹' },
  { code: 'PH', name: 'Filipiny', flag: '🇵🇭' },
  { code: 'FI', name: 'Finlandia', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fidżi', flag: '🇫🇯' },
  { code: 'FR', name: 'Francja', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'Gruzja', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: 'GR', name: 'Grecja', flag: '🇬🇷' },
  { code: 'GL', name: 'Grenlandia', flag: '🇬🇱' },
  { code: 'GP', name: 'Gwadelupa', flag: '🇬🇵' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺' },
  { code: 'GT', name: 'Gwatemala', flag: '🇬🇹' },
  { code: 'GF', name: 'Gujana Francuska', flag: '🇬🇫' },
  { code: 'GG', name: 'Guernsey', flag: '🇬🇬' },
  { code: 'GN', name: 'Gwinea', flag: '🇬🇳' },
  { code: 'GQ', name: 'Gwinea Równikowa', flag: '🇬🇶' },
  { code: 'GW', name: 'Gwinea Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Gujana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HK', name: 'Hongkong', flag: '🇭🇰' },
  { code: 'HU', name: 'Węgry', flag: '🇭🇺' },
  { code: 'IN', name: 'Indie', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonezja', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶' },
  { code: 'IE', name: 'Irlandia', flag: '🇮🇪' },
  { code: 'IS', name: 'Islandia', flag: '🇮🇸' },
  { code: 'IL', name: 'Izrael', flag: '🇮🇱' },
  { code: 'IT', name: 'Włochy', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamajka', flag: '🇯🇲' },
  { code: 'JP', name: 'Japonia', flag: '🇯🇵' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪' },
    { code: 'JO', name: 'Jordania', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazachstan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenia', flag: '🇰🇪' },
  { code: 'KG', name: 'Kirgistan', flag: '🇰🇬' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'KW', name: 'Kuwejt', flag: '🇰🇼' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LV', name: 'Łotwa', flag: '🇱🇻' },
  { code: 'LB', name: 'Liban', flag: '🇱🇧' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'Libia', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Litwa', flag: '🇱🇹' },
  { code: 'LU', name: 'Luksemburg', flag: '🇱🇺' },
  { code: 'MO', name: 'Makau', flag: '🇲🇴' },
  { code: 'MK', name: 'Macedonia Północna', flag: '🇲🇰' },
  { code: 'MG', name: 'Madagaskar', flag: '🇲🇬' },
  { code: 'MY', name: 'Malezja', flag: '🇲🇾' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MV', name: 'Malediwy', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MA', name: 'Maroko', flag: '🇲🇦' },
  { code: 'MQ', name: 'Martynika', flag: '🇲🇶' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'MR', name: 'Mauretania', flag: '🇲🇷' },
  { code: 'YT', name: 'Majotta', flag: '🇾🇹' },
  { code: 'MX', name: 'Meksyk', flag: '🇲🇽' },
  { code: 'FM', name: 'Mikronezja', flag: '🇫🇲' },
  { code: 'MD', name: 'Mołdawia', flag: '🇲🇩' },
  { code: 'MC', name: 'Monako', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', name: 'Czarnogóra', flag: '🇲🇪' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸' },
  { code: 'MZ', name: 'Mozambik', flag: '🇲🇿' },
  { code: 'MM', name: 'Mjanma', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NI', name: 'Nikaragua', flag: '🇳🇮' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺' },
  { code: 'NO', name: 'Norwegia', flag: '🇳🇴' },
  { code: 'NC', name: 'Nowa Kaledonia', flag: '🇳🇨' },
  { code: 'NZ', name: 'Nowa Zelandia', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'NL', name: 'Niderlandy', flag: '🇳🇱' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'PS', name: 'Palestyna', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua-Nowa Gwinea', flag: '🇵🇬' },
  { code: 'PY', name: 'Paragwaj', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'PF', name: 'Polinezja Francuska', flag: '🇵🇫' },
  { code: 'PL', name: 'Polska', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugalia', flag: '🇵🇹' },
  { code: 'PR', name: 'Portoryko', flag: '🇵🇷' },
  { code: 'QA', name: 'Katar', flag: '🇶🇦' },
  { code: 'GB', name: 'Wielka Brytania', flag: '🇬🇧' },
  { code: 'CF', name: 'Republika Środkowoafrykańska', flag: '🇨🇫' },
  { code: 'CZ', name: 'Czechy', flag: '🇨🇿' },
  { code: 'CD', name: 'Demokratyczna Republika Konga', flag: '🇨🇩' },
  { code: 'DO', name: 'Dominikana', flag: '🇩🇴' },
  { code: 'RE', name: 'Reunion', flag: '🇷🇪' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'RO', name: 'Rumunia', flag: '🇷🇴' },
  { code: 'RU', name: 'Rosja', flag: '🇷🇺' },
  { code: 'EH', name: 'Sahara Zachodnia', flag: '🇪🇭' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'AS', name: 'Samoa Amerykańskie', flag: '🇦🇸' },
  { code: 'BL', name: 'Saint-Barthélemy', flag: '🇧🇱' },
  { code: 'KN', name: 'Saint Kitts i Nevis', flag: '🇰🇳' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'MF', name: 'Saint Martin', flag: '🇲🇫' },
  { code: 'PM', name: 'Saint-Pierre i Miquelon', flag: '🇵🇲' },
  { code: 'VC', name: 'Saint Vincent i Grenadyny', flag: '🇻🇨' },
  { code: 'SH', name: 'Wyspa Świętej Heleny', flag: '🇸🇭' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'ST', name: 'Wyspy Świętego Tomasza i Książęca', flag: '🇸🇹' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SC', name: 'Seszele', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapur', flag: '🇸🇬' },
  { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'ZA', name: 'Republika Południowej Afryki', flag: '🇿🇦' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SS', name: 'Sudan Południowy', flag: '🇸🇸' },
  { code: 'SE', name: 'Szwecja', flag: '🇸🇪' },
  { code: 'CH', name: 'Szwajcaria', flag: '🇨🇭' },
  { code: 'SR', name: 'Surinam', flag: '🇸🇷' },
  { code: 'SJ', name: 'Svalbard i Jan Mayen', flag: '🇸🇯' },
  { code: 'TH', name: 'Tajlandia', flag: '🇹🇭' },
  { code: 'TW', name: 'Tajwan', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'TJ', name: 'Tadżykistan', flag: '🇹🇯' },
  { code: 'IO', name: 'Brytyjskie Terytorium Oceanu Indyjskiego', flag: '🇮🇴' },
  { code: 'TF', name: 'Francuskie Terytoria Południowe', flag: '🇹🇫' },
  { code: 'TL', name: 'Timor Wschodni', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trynidad i Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunezja', flag: '🇹🇳' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TR', name: 'Turcja', flag: '🇹🇷' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UA', name: 'Ukraina', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UY', name: 'Urugwaj', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VA', name: 'Watykan', flag: '🇻🇦' },
  { code: 'VE', name: 'Wenezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Wietnam', flag: '🇻🇳' },
  { code: 'WF', name: 'Wallis i Futuna', flag: '🇼🇫' },
  { code: 'YE', name: 'Jemen', flag: '🇾🇪' },
  { code: 'DJ', name: 'Dżibuti', flag: '🇩🇯' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' }
];

export default countries;