import assert from "node:assert/strict";
import test from "node:test";
import {
  BOOTSTRAP_TENANT_AUDIT_LEVEL, BOOTSTRAP_TENANT_AUDIT_METADATA_FIELDS,
  BOOTSTRAP_TENANT_AUDIT_OPERATION, BOOTSTRAP_TENANT_OPERATION,
  BOOTSTRAP_TENANT_RESOURCE_TYPE, COMMAND_TYPES, PRIVILEGED_COMMAND_STAGES,
  bootstrapTenantBehavioralPayload, isPrivilegedCommandStageAllowed,
  validateBootstrapTenantInput, validateBootstrapTenantResult,
} from "@mipymetic/saas-contracts/commands";
import {
  encodeMembershipUidKey, validateMembershipKey, validatePersistedTenant,
  validateTenantAdminAuthorityState, validateTenantBranding, validateTenantSettings,
} from "@mipymetic/saas-contracts/persistence";

const instant = "2026-08-13T12:00:00.000Z";
const tenant = { tenantId:"tenant-1",tenantType:"university",displayName:"Tenant",shortName:"T",country:"PL",locale:"pl-PL",timezone:"Europe/Warsaw",status:"active",createdAt:instant,updatedAt:instant,suspendedAt:null,archivedAt:null };
const settings = { tenantId:"tenant-1",defaultLocale:"pl-PL",registrationPolicy:{openRegistration:false,invitationOnly:false,institutionalEmailOnly:false,manualApprovalRequired:true},featureFlags:{beta:false},supportEmail:null,supportUrl:null,updatedAt:instant };
const branding = { tenantId:"tenant-1",displayName:null,logoUrl:null,faviconUrl:null,colors:{primary:"#000",secondary:"#fff",accent:"#f00"},updatedAt:instant };
const input = { commandId:"command-1",correlationId:"correlation-1",tenantId:"tenant-1",tenant:{tenantType:"university",displayName:"Tenant",shortName:"T",country:"PL",locale:"pl-PL",timezone:"Europe/Warsaw"},settings:{...settings,tenantId:undefined,updatedAt:undefined},branding:{...branding,tenantId:undefined,updatedAt:undefined},firstAdminUid:"admin-1",expectedAdminEmail:"admin@example.test",initialStatus:"active" };
delete input.settings.tenantId; delete input.settings.updatedAt; delete input.branding.tenantId; delete input.branding.updatedAt;

test("BootstrapTenant input and behavioral payload are exact",()=>{assert.equal(validateBootstrapTenantInput(input).ok,true);assert.equal(validateBootstrapTenantInput({...input,actor:"x"}).ok,false);const behavioral=bootstrapTenantBehavioralPayload(input);assert.equal("commandId" in behavioral,false);assert.equal("correlationId" in behavioral,false);assert.equal(behavioral.expectedAdminEmail,"admin@example.test")});
test("Tenant, Settings and Branding validators reject unknown and malformed fields",()=>{for(const [validator,value] of [[validatePersistedTenant,tenant],[validateTenantSettings,settings],[validateTenantBranding,branding]]){assert.equal(validator(value).ok,true);assert.equal(validator({...value,extra:true}).ok,false)}assert.equal(validatePersistedTenant({...tenant,status:"suspended"}).ok,false);assert.equal(validateTenantSettings({...settings,featureFlags:{bad:"yes"}}).ok,false);assert.equal(validateTenantSettings({...settings,supportUrl:"http://example.test"}).ok,false);assert.equal(validateTenantSettings({...settings,supportUrl:"https://example.test/help"}).ok,true);assert.equal(validateTenantBranding({...branding,colors:{primary:"x",secondary:"y"}}).ok,false)});
test("MembershipKey encoding is canonical and validator supports null origin",()=>{assert.equal(encodeMembershipUidKey("abc"),"u1_YWJj");assert.equal(encodeMembershipUidKey("\u017c\u00f3\u0142\u0107"),"u1_xbzDs8WCxIc");assert.notEqual(encodeMembershipUidKey("a"),encodeMembershipUidKey("b"));assert.doesNotMatch(encodeMembershipUidKey("abc"),/=/u);for(const invalid of [""," ",".","..","a/b"])assert.throws(()=>encodeMembershipUidKey(invalid));const key={tenantId:"tenant-1",uid:"admin-1",membershipId:"member-1",status:"approved",originRequestId:null,updatedAt:instant};assert.equal(validateMembershipKey(key).ok,true);assert.equal(validateMembershipKey({...key,status:"removed"}).ok,false);assert.equal(validateMembershipKey({...key,extra:true}).ok,false)});
test("tenant-admin Authority State validates initial tuple",()=>{const state={tenantId:"tenant-1",activeCount:1,revision:1,lastCommandId:"command-1",updatedAt:instant};assert.equal(validateTenantAdminAuthorityState(state).ok,true);for(const value of [-1,1.5,Infinity])assert.equal(validateTenantAdminAuthorityState({...state,activeCount:value}).ok,false);assert.equal(validateTenantAdminAuthorityState({...state,lastCommandId:"a/b"}).ok,false)});
test("BootstrapTenant result, audit literals and stage authorization remain narrow",()=>{const result={commandId:"command-1",correlationId:"correlation-1",operation:BOOTSTRAP_TENANT_OPERATION,resourceType:BOOTSTRAP_TENANT_RESOURCE_TYPE,resourceId:"tenant-1",status:"succeeded",replayed:false};assert.equal(validateBootstrapTenantResult(result).ok,true);assert.equal(validateBootstrapTenantResult({...result,membershipId:"member-1"}).ok,false);assert.equal(BOOTSTRAP_TENANT_AUDIT_OPERATION,"BootstrapTenant.create");assert.equal(BOOTSTRAP_TENANT_AUDIT_LEVEL,"critical");assert.deepEqual(BOOTSTRAP_TENANT_AUDIT_METADATA_FIELDS,["stage","tenantType"]);assert.equal(isPrivilegedCommandStageAllowed(COMMAND_TYPES.BOOTSTRAP_TENANT,PRIVILEGED_COMMAND_STAGES.COMPLETED),true);assert.equal(isPrivilegedCommandStageAllowed(COMMAND_TYPES.BOOTSTRAP_TENANT,PRIVILEGED_COMMAND_STAGES.PREPARED),false);assert.equal(isPrivilegedCommandStageAllowed(COMMAND_TYPES.APPROVE_REGISTRATION_REQUEST,PRIVILEGED_COMMAND_STAGES.COMPLETED),false)});
