export const COMMON_ERROR_CODES: Readonly<{
    INVALID_ARGUMENT: "INVALID_ARGUMENT";
    UNAUTHENTICATED: "UNAUTHENTICATED";
    FORBIDDEN: "FORBIDDEN";
    NOT_FOUND: "NOT_FOUND";
    CONFLICT: "CONFLICT";
    FAILED_PRECONDITION: "FAILED_PRECONDITION";
    UNAVAILABLE: "UNAVAILABLE";
    CONTRACT_VIOLATION: "CONTRACT_VIOLATION";
    UNKNOWN: "UNKNOWN";
}>;
export const BACKEND_ERROR_CODES: Readonly<{
    ALREADY_EXISTS: "ALREADY_EXISTS";
    INTERNAL: "INTERNAL";
    INVALID_ARGUMENT: "INVALID_ARGUMENT";
    UNAUTHENTICATED: "UNAUTHENTICATED";
    FORBIDDEN: "FORBIDDEN";
    NOT_FOUND: "NOT_FOUND";
    CONFLICT: "CONFLICT";
    FAILED_PRECONDITION: "FAILED_PRECONDITION";
    UNAVAILABLE: "UNAVAILABLE";
    CONTRACT_VIOLATION: "CONTRACT_VIOLATION";
    UNKNOWN: "UNKNOWN";
}>;
